"""api_v1 package - autogenerated skeleton to implement frontend API.

This package contains URL routes and placeholder views that match the
endpoints used by the `vue3-element-admin-master` frontend. Implement the
actual business logic in the views or split into apps as needed.
"""

__all__ = ["urls", "views"]
