# Generated by Django 5.1.2 on 2026-05-25 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_type', models.CharField(choices=[('file_conversion', '文件转换'), ('ai_workflow', 'AI 工作流'), ('batch_process', '批量处理')], db_index=True, max_length=50, verbose_name='工作流类型')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Celery Task ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='执行状态')),
                ('params', models.JSONField(default=dict, verbose_name='执行参数')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='执行结果')),
                ('error_msg', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_executions', to=settings.AUTH_USER_MODEL, verbose_name='触发用户')),
            ],
            options={
                'verbose_name': '工作流执行记录',
                'verbose_name_plural': '工作流执行记录',
                'db_table': 'workflow_execution',
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['workflow_type', 'status'], name='workflow_ex_workflo_1d8048_idx'), models.Index(fields=['user_id', 'created_at'], name='workflow_ex_user_id_5f8ed6_idx')],
            },
        ),
    ]
