# Generated by Django 5.1.2 on 2026-05-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_v2", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdUploadQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign_name",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="广告活动名称",
                    ),
                ),
                (
                    "shop",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        verbose_name="店铺名称",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        max_length=10,
                        verbose_name="国家/站点",
                    ),
                ),
                (
                    "ad_type",
                    models.CharField(
                        default="sp",
                        max_length=20,
                        verbose_name="广告类型",
                    ),
                ),
                (
                    "skus",
                    models.JSONField(
                        default=list,
                        verbose_name="SKU 列表",
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        default=list,
                        verbose_name="关键词列表",
                    ),
                ),
                (
                    "parse_status",
                    models.IntegerField(
                        choices=[(0, "解析失败"), (1, "解析成功")],
                        db_index=True,
                        default=1,
                        verbose_name="解析状态",
                    ),
                ),
                (
                    "msg",
                    models.TextField(
                        default="成功",
                        verbose_name="状态消息",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ad_upload_queues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "广告上传队列",
                "verbose_name_plural": "广告上传队列",
                "db_table": "api_v2_ad_upload_queue",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shop", "country"],
                        name="adqueue_shop_country_idx",
                    ),
                ],
            },
        ),
    ]
