# Generated by Django 5.1.2 on 2026-06-02 11:29

import api_v2.models.ad_upload_queue
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0012_refactor_aduploadqueue_to_json_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aduploadqueue',
            name='params',
            field=models.JSONField(default=api_v2.models.ad_upload_queue._default_params, verbose_name='广告参数'),
        ),
        migrations.AlterField(
            model_name='aduploadqueue',
            name='step_ids',
            field=models.JSONField(default=api_v2.models.ad_upload_queue._default_step_ids, verbose_name='步骤产出 ID'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='workflow_type',
            field=models.CharField(choices=[('listing_image_upload', 'Listing 图片上传')], db_index=True, max_length=50, verbose_name='工作流类型'),
        ),
        migrations.CreateModel(
            name='AdTimePricingHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.BigIntegerField(verbose_name='广告活动 ID')),
                ('profile_id', models.BigIntegerField(verbose_name='店铺 Profile ID')),
                ('targeting_type', models.CharField(choices=[('auto', '自动投放'), ('manual', '手动投放')], default='auto', max_length=20, verbose_name='投放类型')),
                ('timezone', models.CharField(default='', max_length=50, verbose_name='时区')),
                ('hit_auto_bid_rules', models.CharField(default='', help_text='命中的自动竞价规则 ID（单条）', max_length=255, verbose_name='命中自动竞价规则')),
                ('hit_time_pricing_rules', models.CharField(default='', help_text='命中的策略 ID（单条）', max_length=500, verbose_name='命中分时策略规则')),
                ('is_time_pricing', models.IntegerField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否正在分时')),
                ('default_bid_rules', models.JSONField(default=list, help_text='竞价规则字符串列表', verbose_name='默认竞价规则')),
                ('user_manual_bid_rules', models.JSONField(default=list, help_text='竞价规则字符串列表', verbose_name='用户手动设置竞价规则')),
                ('user_manual_time_rules', models.JSONField(default=list, help_text='用户手动设置的分时规则字符串列表', verbose_name='用户手动设置分时规则')),
                ('is_manual_rules', models.IntegerField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否手动设置规则')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '广告分时策略命中记录',
                'verbose_name_plural': '广告分时策略命中记录',
                'db_table': 'ad_time_pricing_hit',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign_id', 'profile_id'], name='ad_time_pri_campaig_95d1f8_idx')],
                'unique_together': {('campaign_id', 'profile_id')},
            },
        ),
        migrations.CreateModel(
            name='SpBidAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.BigIntegerField(blank=True, help_text='与 keyword_id 互斥，只能存在一个', null=True, verbose_name='定位组 ID')),
                ('keyword_id', models.BigIntegerField(blank=True, help_text='与 target_id 互斥，只能存在一个', null=True, verbose_name='关键词 ID')),
                ('campaign_id', models.BigIntegerField(verbose_name='广告活动 ID')),
                ('profile_id', models.BigIntegerField(verbose_name='店铺 ID')),
                ('execution_type', models.CharField(choices=[('TIME_PRICING_START', '分时开始'), ('TIME_PRICING_CALLBACK', '分时回调'), ('BID_ADJUSTMENT', '竞价调整')], max_length=50, verbose_name='执行类型')),
                ('time_pricing_rule_id', models.BigIntegerField(blank=True, help_text='分时策略命中时写入关联的策略 ID', null=True, verbose_name='分时规则 ID')),
                ('auto_rule_id', models.BigIntegerField(blank=True, help_text='自动竞价规则命中时写入关联的规则 ID', null=True, verbose_name='自动竞价规则 ID')),
                ('is_time_pricing', models.IntegerField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否正在分时')),
                ('bid_before', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='调整前竞价')),
                ('bid_after', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='调整后竞价')),
                ('adjustment_status', models.CharField(choices=[('PENDING', '待执行'), ('SUCCESS', '成功'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='调整状态')),
                ('adjustment_time', models.DateTimeField(blank=True, null=True, verbose_name='调整时间')),
                ('execution_status', models.CharField(choices=[('PENDING', '待执行'), ('RUNNING', '执行中'), ('SUCCESS', '成功'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='执行状态')),
                ('msg', models.TextField(blank=True, default='', verbose_name='执行日志回写')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'SP 广告商品投放调整记录',
                'verbose_name_plural': 'SP 广告商品投放调整记录',
                'db_table': 'sp_bid_adjustment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign_id', 'profile_id'], name='sp_bid_adju_campaig_07752b_idx'), models.Index(fields=['execution_type'], name='sp_bid_adju_executi_55eea1_idx'), models.Index(fields=['execution_status'], name='sp_bid_adju_executi_06777b_idx'), models.Index(fields=['adjustment_time'], name='sp_bid_adju_adjustm_3ab009_idx')],
            },
        ),
    ]
