# Generated by Django 5.1.2 on 2026-06-02 08:40

import api_v2.models.ad_upload_queue
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0012_refactor_aduploadqueue_to_json_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aduploadqueue',
            name='params',
            field=models.JSONField(default=api_v2.models.ad_upload_queue._default_params, verbose_name='广告参数'),
        ),
        migrations.AlterField(
            model_name='aduploadqueue',
            name='step_ids',
            field=models.JSONField(default=api_v2.models.ad_upload_queue._default_step_ids, verbose_name='步骤产出 ID'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='workflow_type',
            field=models.CharField(choices=[('listing_image_upload', 'Listing 图片上传')], db_index=True, max_length=50, verbose_name='工作流类型'),
        ),
        migrations.CreateModel(
            name='AdTimePricingHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.BigIntegerField(verbose_name='广告活动 ID')),
                ('profile_id', models.BigIntegerField(verbose_name='店铺 Profile ID')),
                ('hit_auto_bid_rules', models.CharField(default='', max_length=255, verbose_name='命中自动竞价规则')),
                ('hit_time_pricing_rules', models.CharField(default='', help_text='命中策略的名称，多条用逗号分隔', max_length=500, verbose_name='命中分时策略规则')),
                ('is_time_pricing', models.IntegerField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否正在分时')),
                ('default_bid_rules', models.JSONField(default=list, help_text='竞价规则字符串列表', verbose_name='默认竞价规则')),
                ('user_manual_bid_rules', models.JSONField(default=list, help_text='竞价规则字符串列表', verbose_name='用户手动设置竞价规则')),
                ('is_manual_rules', models.IntegerField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否手动设置规则')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '广告分时策略命中记录',
                'verbose_name_plural': '广告分时策略命中记录',
                'db_table': 'ad_time_pricing_hit',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign_id', 'profile_id'], name='ad_time_pri_campaig_95d1f8_idx')],
                'unique_together': {('campaign_id', 'profile_id')},
            },
        ),
    ]
