# Generated by Django 5.1.2 on 2026-06-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0013_add_time_pricing_and_bid_adjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxApiErr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='', help_text='如 bid_adjustment / time_pricing_callback', max_length=100, verbose_name='任务标识')),
                ('task_name', models.CharField(default='', help_text='如 竞价调整 / 分时回调', max_length=200, verbose_name='任务名')),
                ('url', models.CharField(default='', max_length=500, verbose_name='请求接口')),
                ('method', models.CharField(default='POST', max_length=10, verbose_name='请求方法')),
                ('parameter', models.TextField(blank=True, default='', help_text='请求体 JSON 文本（截断至 5000 字符）', verbose_name='请求参数')),
                ('code', models.CharField(default='', help_text='HTTP 状态码或 API 返回的 code 字段', max_length=20, verbose_name='状态/响应码')),
                ('message', models.TextField(blank=True, default='', help_text='错误信息或 API 返回的 message', verbose_name='信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
            ],
            options={
                'verbose_name': '领星API调用错误日志',
                'verbose_name_plural': '领星API调用错误日志',
                'db_table': 'lx_api_err',
                'ordering': ['-created_at'],
            },
        ),
    ]
