# Generated by Django 5.1.2 on 2026-06-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0013_add_time_pricing_and_bid_adjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxApiErr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='', help_text='如 bid_adjustment / time_pricing_callback', max_length=100, verbose_name='任务标识')),
                ('task_name', models.CharField(default='', help_text='如 竞价调整 / 分时回调', max_length=200, verbose_name='任务名')),
                ('url', models.CharField(default='', max_length=500, verbose_name='请求接口')),
                ('method', models.CharField(default='POST', max_length=10, verbose_name='请求方法')),
                ('parameter', models.TextField(blank=True, default='', help_text='请求体 JSON 文本', verbose_name='请求参数')),
                ('code', models.CharField(default='', help_text='HTTP 状态码或 API 返回的 code 字段', max_length=20, verbose_name='状态/响应码')),
                ('message', models.TextField(blank=True, default='', help_text='错误信息或 API 返回的 message', verbose_name='信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
            ],
            options={
                'verbose_name': '领星API调用错误日志',
                'verbose_name_plural': '领星API调用错误日志',
                'db_table': 'lx_api_err',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='adtimepricinghit',
            name='default_bid_rules',
        ),
        migrations.RemoveField(
            model_name='adtimepricinghit',
            name='hit_auto_bid_rules',
        ),
        migrations.RemoveField(
            model_name='adtimepricinghit',
            name='user_manual_bid_rules',
        ),
        migrations.RemoveField(
            model_name='adtimepricinghit',
            name='user_manual_time_rules',
        ),
        migrations.AddField(
            model_name='adtimepricinghit',
            name='is_callback',
            field=models.IntegerField(choices=[(1, '是'), (0, '否')], default=0, help_text='该条记录是否已执行回调', verbose_name='是否回调'),
        ),
        migrations.AddField(
            model_name='adtimepricinghit',
            name='manual_rule_id',
            field=models.CharField(default='', help_text='用户手动指定的规则 ID', max_length=500, verbose_name='用户设置规则的 ID'),
        ),
        migrations.AddField(
            model_name='adtimepricinghit',
            name='rule_updated_today',
            field=models.BooleanField(default=False, help_text='当日是否已重新匹配过规则', verbose_name='当日规则是否更新'),
        ),
        migrations.AddField(
            model_name='adtimepricinghit',
            name='time_end',
            field=models.DateTimeField(blank=True, help_text='本次分时结束的回调时间（当地站点时间）', null=True, verbose_name='分时结束时间'),
        ),
        migrations.AddField(
            model_name='adtimepricinghit',
            name='time_end_cn',
            field=models.DateTimeField(blank=True, help_text='本次分时结束的回调时间（Asia/Shanghai）', null=True, verbose_name='分时结束时间-中国'),
        ),
        migrations.AddField(
            model_name='adtimepricinghit',
            name='time_start',
            field=models.DateTimeField(blank=True, help_text='本次分时生效的开始时间（当地站点时间）', null=True, verbose_name='分时开始时间'),
        ),
        migrations.AddField(
            model_name='adtimepricinghit',
            name='time_start_cn',
            field=models.DateTimeField(blank=True, help_text='本次分时生效的开始时间（Asia/Shanghai）', null=True, verbose_name='分时开始时间-中国'),
        ),
    ]
