# Generated by Django 5.1.2 on 2026-06-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0014_add_lx_api_err_and_update_hit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adtimepricinghit',
            name='is_callback',
        ),
        migrations.AddField(
            model_name='adtimepricinghit',
            name='awaiting_start',
            field=models.IntegerField(choices=[(1, '等待分时开始'), (0, '分时生效中')], default=1, help_text='YES(1)=等待分时开始（已回调/新命中）；NO(0)=分时生效中（正在降价，等待回调）', verbose_name='是否等待分时开始'),
        ),
        migrations.AddField(
            model_name='adtimepricinghit',
            name='error_count',
            field=models.IntegerField(default=0, help_text='连续处理失败的次数，达到阈值后跳过该记录以防止无限重试', verbose_name='连续失败次数'),
        ),
        migrations.AddField(
            model_name='adtimepricinghit',
            name='segment_times',
            field=models.JSONField(default=list, help_text='每个子时段的独立时间边界与规则列表。格式：[{"index": 0, "start_cn": "...", "end_cn": "...", "rules": [...]}]。空列表时降级为合并窗口逻辑（兼容旧数据）。', verbose_name='子时段明细'),
        ),
        migrations.AlterField(
            model_name='adtimepricinghit',
            name='is_time_pricing',
            field=models.IntegerField(choices=[(1, '等待分时开始'), (0, '分时生效中')], default=0, verbose_name='是否正在分时'),
        ),
        migrations.AlterField(
            model_name='spbidadjustment',
            name='is_time_pricing',
            field=models.IntegerField(choices=[(1, '等待分时开始'), (0, '分时生效中')], default=0, verbose_name='是否正在分时'),
        ),
    ]
