# Generated by Claude Opus — 分时调价系统 14 个隐患修复
# 新增 segment_times、awaiting_start、error_count 字段；
# 通过 RunPython 迁移 is_callback → awaiting_start 数据。

from django.db import migrations, models


def migrate_is_callback_to_awaiting_start(apps, schema_editor):
    """将 is_callback 数据迁移到 awaiting_start：值相同（0↔0, 1↔1）。"""
    AdTimePricingHit = apps.get_model("api_v2", "AdTimePricingHit")
    AdTimePricingHit.objects.using(schema_editor.connection.alias).update(
        awaiting_start=models.F("is_callback"),
    )


def reverse_awaiting_start_to_is_callback(apps, schema_editor):
    """逆向回迁：将 awaiting_start 数据回写到 is_callback。"""
    AdTimePricingHit = apps.get_model("api_v2", "AdTimePricingHit")
    AdTimePricingHit.objects.using(schema_editor.connection.alias).update(
        is_callback=models.F("awaiting_start"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("api_v2", "0014_add_lx_api_err_and_update_hit"),
    ]

    operations = [
        # ── 新增字段 ──
        migrations.AddField(
            model_name="adtimepricinghit",
            name="awaiting_start",
            field=models.IntegerField(
                choices=[(1, "等待分时开始"), (0, "分时生效中")],
                default=1,
                help_text="YES(1)=等待分时开始（已回调/新命中）；NO(0)=分时生效中（正在降价，等待回调）",
                verbose_name="是否等待分时开始",
            ),
        ),
        migrations.AddField(
            model_name="adtimepricinghit",
            name="error_count",
            field=models.IntegerField(
                default=0,
                help_text="连续处理失败的次数，达到阈值后跳过该记录以防止无限重试",
                verbose_name="连续失败次数",
            ),
        ),
        migrations.AddField(
            model_name="adtimepricinghit",
            name="segment_times",
            field=models.JSONField(
                default=list,
                help_text='每个子时段的独立时间边界与规则列表。格式：[{"index": 0, "start_cn": "...", "end_cn": "...", "rules": [...]}]。空列表时降级为合并窗口逻辑（兼容旧数据）。',
                verbose_name="子时段明细",
            ),
        ),

        # ── 数据迁移：is_callback → awaiting_start ──
        migrations.RunPython(
            code=migrate_is_callback_to_awaiting_start,
            reverse_code=reverse_awaiting_start_to_is_callback,
        ),

        # ── 更新 TimePricingHitStatus choices 的中文标签 ──
        # 注意：is_time_pricing 字段也会受 choices 变更影响，但值不变（0↔0, 1↔1）
        migrations.AlterField(
            model_name="adtimepricinghit",
            name="is_time_pricing",
            field=models.IntegerField(
                choices=[(1, "等待分时开始"), (0, "分时生效中")],
                default=0,
                verbose_name="是否正在分时",
            ),
        ),
        migrations.AlterField(
            model_name="adtimepricinghit",
            name="is_callback",
            field=models.IntegerField(
                choices=[(1, "等待分时开始"), (0, "分时生效中")],
                default=0,
                help_text="【已废弃】请使用 awaiting_start。该字段保留用于平滑过渡，后续版本将删除。",
                verbose_name="是否回调（已废弃）",
            ),
        ),
        migrations.AlterField(
            model_name="spbidadjustment",
            name="is_time_pricing",
            field=models.IntegerField(
                choices=[(1, "等待分时开始"), (0, "分时生效中")],
                default=0,
                verbose_name="是否正在分时",
            ),
        ),
    ]
