export const defaultColumns = [
  {
    prop: "image",
    label: "图片",
    visible: true,
    fixed: "left",
    width: 69,
    align: "center",
    category: "基础信息",
  },
  {
    prop: "msku",
    label: "MSKU/FNSKU",
    visible: true,
    fixed: "left",
    width: 145,
    category: "基础信息",
    sortable: "custom",
  },
  {
    prop: "skuName",
    label: "品名/SKU",
    visible: true,
    fixed: "left",
    width: 140,
    category: "基础信息",
    sortable: "custom",
  },
  { prop: "shop", label: "店铺", visible: true, width: 100, category: "基础信息" },
  { prop: "country", label: "国家", visible: true, width: 75, category: "基础信息" },
  { prop: "assort", label: "分类", visible: true, width: 80, category: "基础信息" },
  {
    prop: "status",
    label: "状态",
    visible: true,
    fixed: false,
    width: 80,
    align: "center",
    category: "基础信息",
  },
  {
    prop: "open_date_time",
    label: "创建时间",
    visible: true,
    width: 170,
    category: "其他信息",
    sortable: "custom",
  },
  { prop: "asin", label: "ASIN", visible: true, fixed: false, width: 120, category: "基础信息" },
  { prop: "parentAsin", label: "父ASIN", visible: true, width: 120, category: "基础信息" },
  {
    prop: "label",
    label: "标签",
    visible: true,
    width: 100,
    align: "center",
    category: "基础信息",
  },
  {
    prop: "title",
    label: "标题",
    visible: true,
    fixed: false,
    width: 180,
    showOverflowTooltip: false, // 改为手动控制 tooltip
    category: "基础信息",
  },
  { prop: "price", label: "价格", visible: true, width: 80, align: "right", category: "库存价格" },
  {
    prop: "totalPrice",
    label: "售价(总价)",
    visible: true,
    width: 100,
    align: "right",
    category: "库存价格",
  },
  {
    prop: "discountPrice",
    label: "优惠价",
    visible: true,
    width: 90,
    align: "right",
    category: "库存价格",
  },
  {
    prop: "fbaSellable",
    label: "FBA可售",
    visible: true,
    width: 90,
    align: "right",
    category: "库存价格",
  },
  {
    prop: "estFbaFee",
    label: "预估FBA费",
    visible: true,
    width: 100,
    align: "right",
    category: "库存价格",
  },
  {
    prop: "referralFee",
    label: "平台费",
    visible: true,
    width: 80,
    align: "right",
    category: "库存价格",
  },
  {
    prop: "salesToday",
    label: "今日销量",
    visible: true,
    width: 110,
    align: "right",
    category: "销售数据",
    sortable: "custom",
  },
  {
    prop: "salesYesterday",
    label: "昨日销量",
    visible: true,
    width: 110,
    align: "right",
    category: "销售数据",
    sortable: "custom",
  },
  {
    prop: "sales7_14_30",
    label: "7|14|30天销量",
    visible: true,
    width: 130,
    align: "center",
    category: "销售数据",
  },
  {
    prop: "rank",
    label: "大类排名",
    visible: true,
    width: 120,
    align: "left",
    category: "销售数据",
    sortable: "custom",
  },
  {
    prop: "profit",
    label: "订单毛利率/毛利润",
    visible: true,
    width: 180,
    align: "right",
    category: "销售数据",
    sortable: "custom",
  },
  {
    prop: "avgSales7_14_30",
    label: "7|14|30日均销量",
    visible: true,
    width: 140,
    align: "center",
    category: "销售数据",
  },
  {
    prop: "salesAmountYesterday",
    label: "昨日销售额",
    visible: true,
    width: 110,
    align: "right",
    category: "销售数据",
  },
  {
    prop: "salesAmount7_14_30",
    label: "7|14|30天销售额",
    visible: true,
    width: 150,
    align: "center",
    category: "销售数据",
  },
  {
    prop: "adCostYesterday",
    label: "昨日广告费",
    visible: true,
    width: 120,
    align: "right",
    category: "销售数据",
    sortable: "custom",
  },
  {
    prop: "adCost7_14_30",
    label: "7|14|30天广告费",
    visible: true,
    width: 150,
    align: "center",
    category: "销售数据",
  },
  {
    prop: "smallRank",
    label: "小类排名",
    visible: true,
    width: 120,
    align: "left",
    category: "销售数据",
    sortable: "custom",
  },
  {
    prop: "rating",
    label: "评分/Rating总数",
    visible: true,
    width: 150,
    align: "right",
    category: "销售数据",
  },
  {
    prop: "openTime",
    label: "开售时间",
    visible: true,
    width: 120,
    category: "其他信息",
    sortable: "custom",
  },
  {
    prop: "firstOrderTime",
    label: "首单时间",
    visible: true,
    width: 110,
    category: "其他信息",
    sortable: "custom",
  },
  { prop: "pairType", label: "配对方式", visible: true, width: 100, category: "其他信息" },
  { prop: "owner", label: "负责人", visible: true, width: 80, category: "其他信息" },
  {
    prop: "remarks",
    label: "备注",
    visible: true,
    fixed: "right",
    width: 150,
    category: "其他信息",
  },
  // 补充 test.html 中的其他列（默认隐藏）
  { prop: "fulfillment", label: "配送方式", visible: false, width: 90, category: "基础信息" },
  { prop: "brand", label: "亚马逊品牌", visible: false, width: 99, category: "基础信息" },
  { prop: "productCode", label: "商品编码", visible: false, width: 150, category: "基础信息" },
  { prop: "variants", label: "变体属性", visible: false, width: 100, category: "基础信息" },
  {
    prop: "b2bPrice",
    label: "B2B价格",
    visible: false,
    width: 100,
    align: "right",
    category: "库存价格",
  },
  {
    prop: "listPrice",
    label: "List Price",
    visible: false,
    width: 100,
    align: "right",
    category: "库存价格",
  },
  {
    prop: "fbmStock",
    label: "FBM库存",
    visible: false,
    width: 100,
    align: "right",
    category: "库存价格",
  },
];

export const listingStatusOptions = [
  { label: "在售", value: "on" },
  { label: "停售", value: "off" },
  { label: "已删除", value: "deleted" },
];

export const pairStatusOptions = [
  { label: "已配对", value: "paired" },
  { label: "未配对", value: "unpaired" },
];

export const categoryTypeOptions = [
  { label: "饰品", value: "饰品" },
  { label: "普货", value: "普货" },
  { label: "正常服装", value: "正常服装" },
  { label: "情趣服装", value: "情趣服装" },
  { label: "其他", value: "其他" },
  { label: "无", value: "无" },
];

export const searchTypeOptions = [
  { label: "SKU", value: "sku" },
  { label: "MSKU", value: "seller_sku" },
  { label: "ASIN", value: "asin" },
  { label: "标签", value: "tag" },
];
