# Generated by hand to add route_name field and External type to Menu
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='route_name',
            field=models.CharField(max_length=100, blank=True, default='', help_text='路由名称 name'),
        ),
        # Note: choices updates do not require a schema change beyond code; this migration ensures consistency with new code
    ]
