# Generated by Copilot on 2025-11-08
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_v1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictitem",
            name="tag_type",
            field=models.CharField(max_length=20, blank=True, default=""),
        ),
    ]
