# Generated by Copilot on 2025-11-08
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_merge_0002_menu_route_name_and_external_0002_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='data_scope',
            field=models.IntegerField(default=1, help_text='1=全部数据 2=部门及子部门 3=本部门 4=本人'),
        ),
    ]
