# Generated by Copilot on 2025-11-08
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_role_data_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=100, blank=True, default='', help_text='部门编号'),
        ),
    ]
