# Generated by Django 5.2.4 on 2025-11-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_file_management'),
        ('api_v1', '0006_add_tag_type_to_dictitem'),
    ]

    operations = [
    ]
