# Generated by Django 5.2.4 on 2025-11-08 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0007_merge_20251108_1333'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileEntryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_type', models.CharField(default='read', max_length=16)),
            ],
            options={
                'verbose_name': '文件夹访问控制',
                'verbose_name_plural': '文件夹访问控制',
            },
        ),
        migrations.RenameIndex(
            model_name='fileentry',
            new_name='api_v1_file_owner_i_f3cae9_idx',
            old_name='api_v1_file_owner__is_d7b3f3_idx',
        ),
        migrations.RenameIndex(
            model_name='fileentry',
            new_name='api_v1_file_parent__bb6acb_idx',
            old_name='api_v1_file_parent__is_5a0d69_idx',
        ),
        migrations.RenameIndex(
            model_name='fileshare',
            new_name='api_v1_file_token_c221d2_idx',
            old_name='api_v1_file_token_94d8bc_idx',
        ),
        migrations.AlterField(
            model_name='fileentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.IntegerField(choices=[(1, 'Directory'), (2, 'Menu'), (3, 'Button'), (4, 'External')], default=2),
        ),
        migrations.AddField(
            model_name='fileentryaccess',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acl_entries', to='api_v1.fileentry'),
        ),
        migrations.AddField(
            model_name='fileentryaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_entry_acls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fileentryaccess',
            index=models.Index(fields=['entry', 'user'], name='api_v1_file_entry_i_d71a92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fileentryaccess',
            unique_together={('entry', 'user')},
        ),
    ]
