# Generated by Django 5.2.4 on 2025-11-08 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0008_fileentryaccess_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fileentry',
            name='sha256',
            field=models.CharField(blank=True, default='', help_text='SHA256 哈希（用于秒传/去重）', max_length=64),
        ),
        migrations.AddIndex(
            model_name='fileentry',
            index=models.Index(fields=['sha256'], name='api_v1_file_sha256_f3dd1b_idx'),
        ),
    ]
