# Generated by Django 5.2.4 on 2025-11-08 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0009_fileentry_sha256_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=16)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hash_task', to='api_v1.fileentry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hash_tasks', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='父级文件夹', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hash_tasks', to='api_v1.fileentry')),
            ],
            options={
                'verbose_name': '哈希任务',
                'verbose_name_plural': '哈希任务',
                'indexes': [models.Index(fields=['owner', 'status'], name='api_v1_hash_owner_i_381246_idx')],
            },
        ),
    ]
