# Generated by Django 5.1.2 on 2025-11-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0010_hashtask'),
    ]

    operations = [
        # Simplify: directly drop the models/tables in an order that removes dependents first.
        migrations.DeleteModel(
            name='FileEntryAccess',
        ),
        migrations.DeleteModel(
            name='FileShare',
        ),
        migrations.DeleteModel(
            name='HashTask',
        ),
        migrations.DeleteModel(
            name='FileObject',
        ),
        migrations.DeleteModel(
            name='FileEntry',
        ),
    ]
