# Generated by Django 5.2.4 on 2025-11-09 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0012_decommission_file_menus_and_logs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(help_text='前端生成的文件夹ID', max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api_v1.filefolder')),
            ],
            options={
                'verbose_name': '文件夹',
                'verbose_name_plural': '文件夹',
            },
        ),
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_id', models.CharField(help_text='前端生成的文件ID', max_length=64, unique=True)),
                ('merge_file_id', models.CharField(help_text='分片阶段合并文件ID', max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('file_hash', models.CharField(db_index=True, max_length=128)),
                ('ext', models.CharField(blank=True, default='', max_length=50)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('total_chunks', models.IntegerField(default=0)),
                ('uploaded_chunks', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('storage_path', models.CharField(blank=True, default='', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='api_v1.filefolder')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
            },
        ),
        migrations.CreateModel(
            name='FileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_hash', models.CharField(db_index=True, max_length=128)),
                ('num', models.IntegerField()),
                ('size', models.BigIntegerField(default=0)),
                ('storage_path', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api_v1.fileasset')),
            ],
            options={
                'verbose_name': '文件分片',
                'verbose_name_plural': '文件分片',
                'indexes': [models.Index(fields=['chunk_hash'], name='api_v1_file_chunk_h_7c4fa1_idx')],
                'unique_together': {('asset', 'num')},
            },
        ),
        migrations.AddIndex(
            model_name='filefolder',
            index=models.Index(fields=['external_id'], name='api_v1_file_externa_4ac0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='filefolder',
            index=models.Index(fields=['is_deleted'], name='api_v1_file_is_dele_89c03a_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['file_hash'], name='api_v1_file_file_ha_21d318_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['is_deleted', 'is_completed'], name='api_v1_file_is_dele_5ae1d1_idx'),
        ),
    ]
