# Generated by Django 5.2.8 on 2025-11-20 04:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('api_v1', '0013_filefolder_fileasset_filechunk_and_more'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	# Reverted: no operations (migration intentionally left as no-op to avoid applying model removal here).
	operations = []
