# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0014_noticeread'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server_name', models.CharField(max_length=200)),
                ('node', models.CharField(max_length=200)),
                ('ip', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('order_num', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '数据采集节点',
                'verbose_name_plural': '数据采集节点',
                'ordering': ('order_num', 'id'),
            },
        ),
    ]

