# Generated by ChatGPT - manual migration for CrawlerCategory
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0015_crawlerconf'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('category_id', models.CharField(default='', max_length=200, blank=True)),
                ('site', models.CharField(default='', max_length=100, blank=True)),
                ('category_type', models.CharField(default='', max_length=100, blank=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '爬取类目',
                'verbose_name_plural': '爬取类目',
                'ordering': ('-created_at', 'id'),
            },
        ),
    ]
