"""Add CloudAuthToken model

Generated by patch.
"""
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0017_add_cloud_id_to_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.CharField(blank=True, default='', max_length=255)),
                ('token', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '云认证令牌',
                'verbose_name_plural': '云认证令牌',
            },
        ),
    ]
