# Generated by Django 5.2.8 on 2025-11-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0019_alter_crawlercategory_id_noticeread'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.TextField(blank=True, default='')),
                ('level', models.CharField(choices=[('debug', 'debug'), ('info', 'info'), ('warn', 'warn'), ('error', 'error')], default='info', max_length=10)),
                ('elapsed_ms', models.IntegerField(default=0)),
                ('operator', models.CharField(blank=True, default='', max_length=100)),
                ('ip', models.CharField(blank=True, default='', max_length=45)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': '爬虫日志',
                'verbose_name_plural': '爬虫日志',
                'ordering': ('-id',),
            },
        ),
    ]
