# Generated by Django 5.2.8 on 2025-11-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0020_crawlerlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerSellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('order_num', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '卖家精灵账号',
                'verbose_name_plural': '卖家精灵账号',
                'ordering': ('order_num', 'id'),
            },
        ),
        migrations.AlterField(
            model_name='operlog',
            name='action',
            field=models.TextField(),
        ),
    ]
