# Generated by Copilot

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0021_crawlerselleraccount_alter_operlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_group', models.CharField(max_length=255, verbose_name='图片组')),
                ('cloud_path', models.CharField(max_length=500, verbose_name='Cloud 路径')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='状态')),
                ('log', models.TextField(blank=True, null=True, verbose_name='日志')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='图片URL')),
            ],
            options={
                'db_table': 'sys_image_upload',
                'ordering': ['-created_at'],
            },
        ),
    ]
