# Generated by Django 5.1.2 on 2026-01-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0023_notice_level_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProfitCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('params', models.TextField(blank=True, default='')),
                ('data', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'OrderProfit 缓存',
                'verbose_name_plural': 'OrderProfit 缓存',
            },
        ),
    ]
