# Generated by Django 5.1.2 on 2026-01-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0024_orderprofitcache'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderprofitcache',
            index=models.Index(fields=['created_at'], name='api_v1_orde_created_b7836f_idx'),
        ),
    ]
