# Generated by Django 5.1.2 on 2026-01-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0025_orderprofitcache_api_v1_orde_created_b7836f_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLossOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.CharField(blank=True, default='', max_length=512, verbose_name='图片URL')),
                ('msku', models.CharField(blank=True, default='', max_length=200, verbose_name='MSKU')),
                ('asin', models.CharField(blank=True, default='', max_length=50, verbose_name='ASIN')),
                ('parent_asin', models.CharField(blank=True, default='', max_length=50, verbose_name='父ASIN')),
                ('store_country', models.CharField(blank=True, default='', max_length=200, verbose_name='店铺/国家')),
                ('product_name_sku', models.CharField(blank=True, default='', max_length=512, verbose_name='品名/SKU')),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='毛利润')),
                ('gross_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='毛利率')),
                ('net_gross_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='净毛利率')),
                ('return_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='退货率')),
                ('refund_amount_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='退款率')),
                ('total_stock_fee', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='仓储费')),
                ('spend', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='广告费')),
                ('spend_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='广告率费')),
                ('owner', models.CharField(blank=True, default='', max_length=100, verbose_name='负责人')),
                ('month', models.CharField(db_index=True, help_text='YYYY-MM', max_length=7, verbose_name='月份')),
            ],
            options={
                'verbose_name': '月度亏损订单统计',
                'verbose_name_plural': '月度亏损订单统计',
                'ordering': ('-month', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MonthlyLossOrderFirst20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.CharField(blank=True, default='', max_length=512, verbose_name='图片URL')),
                ('msku', models.CharField(blank=True, default='', max_length=200, verbose_name='MSKU')),
                ('asin', models.CharField(blank=True, default='', max_length=50, verbose_name='ASIN')),
                ('parent_asin', models.CharField(blank=True, default='', max_length=50, verbose_name='父ASIN')),
                ('store_country', models.CharField(blank=True, default='', max_length=200, verbose_name='店铺/国家')),
                ('product_name_sku', models.CharField(blank=True, default='', max_length=512, verbose_name='品名/SKU')),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='毛利润')),
                ('gross_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='毛利率')),
                ('net_gross_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='净毛利率')),
                ('return_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='退货率')),
                ('refund_amount_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='退款率')),
                ('total_stock_fee', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='仓储费')),
                ('spend', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='广告费')),
                ('spend_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='广告率费')),
                ('owner', models.CharField(blank=True, default='', max_length=100, verbose_name='负责人')),
                ('month', models.CharField(db_index=True, help_text='YYYY-MM', max_length=7, verbose_name='月份')),
            ],
            options={
                'verbose_name': '月度前20天亏损订单统计',
                'verbose_name_plural': '月度前20天亏损订单统计',
                'ordering': ('-month', '-id'),
            },
        ),
    ]
