# Generated by GitHub Copilot on 2026-01-27
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0026_monthlylossorder_monthlylossorderfirst20'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlylossorder',
            name='sales',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='销量'),
        ),
        migrations.AddField(
            model_name='monthlylossorderfirst20',
            name='sales',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='销量'),
        ),
    ]
