# Generated by Django 5.1.2 on 2026-03-11 01:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0029_salesproductlisting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('msku', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='MSKU')),
                ('sku', models.CharField(blank=True, max_length=255, null=True, verbose_name='SKU')),
                ('classification_type', models.CharField(max_length=100, verbose_name='归类类型')),
            ],
            options={
                'verbose_name': '产品归类',
                'verbose_name_plural': '产品归类',
                'db_table': 'product_classification',
            },
        ),
        migrations.CreateModel(
            name='SolarTermTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asin', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='ASIN')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签列表')),
            ],
            options={
                'verbose_name': '节气标签',
                'verbose_name_plural': '节气标签',
                'db_table': 'solar_term_tag',
            },
        ),
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('daily', '日报'), ('weekly', '周报')], default='daily', max_length=20)),
                ('content', models.TextField(blank=True, default='', help_text='今日工作内容')),
                ('plan', models.TextField(blank=True, default='', help_text='明日计划')),
                ('issues', models.TextField(blank=True, default='', help_text='遇到问题/需要协助')),
                ('work_hours', models.DecimalField(decimal_places=1, default=8.0, help_text='工时', max_digits=4)),
                ('progress', models.IntegerField(default=0, help_text='进度百分比')),
                ('report_date', models.DateField(default=django.utils.timezone.now, help_text='汇报日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '工作汇报',
                'verbose_name_plural': '工作汇报',
                'ordering': ('-report_date', '-created_at'),
            },
        ),
    ]
