# Generated by Django 5.1.2 on 2026-03-11 01:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0028_allow_blank_cloudpath'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('daily', '日报'), ('weekly', '周报')], default='daily', max_length=20)),
                ('content', models.TextField(blank=True, default='', help_text='今日工作内容')),
                ('plan', models.TextField(blank=True, default='', help_text='明日计划')),
                ('issues', models.TextField(blank=True, default='', help_text='遇到问题/需要协助')),
                ('work_hours', models.DecimalField(decimal_places=1, default=8.0, help_text='工时', max_digits=4)),
                ('progress', models.IntegerField(default=0, help_text='进度百分比')),
                ('report_date', models.DateField(default=django.utils.timezone.now, help_text='汇报日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '工作汇报',
                'verbose_name_plural': '工作汇报',
                'ordering': ('-report_date', '-created_at'),
            },
        ),
    ]
