# Generated by Django 5.1.2 on 2026-04-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0030_productclassification_solartermtag_workreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_id', models.CharField(help_text='活动ID', max_length=100, unique=True)),
                ('profile_id', models.CharField(help_text='Profile ID', max_length=100)),
                ('store_id', models.CharField(help_text='Store ID', max_length=100)),
                ('portfolio_id', models.CharField(blank=True, help_text='Portfolio ID', max_length=100, null=True)),
                ('state', models.CharField(help_text='状态', max_length=20)),
                ('sponsored_type', models.CharField(help_text='赞助类型 (sponsored_type)', max_length=50)),
                ('targeting_type', models.CharField(help_text='投放类型 (targeting_type)', max_length=50)),
                ('store_name', models.CharField(blank=True, help_text='店铺', max_length=100, null=True)),
                ('name', models.CharField(help_text='广告活动名称', max_length=255)),
                ('service_status', models.CharField(help_text='服务状态', max_length=50)),
                ('portfolio_name', models.CharField(blank=True, help_text='广告组合', max_length=255, null=True)),
                ('bidding_type', models.CharField(help_text='竞价策略', max_length=50)),
                ('start_date', models.DateField(blank=True, help_text='开始日期', null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='预算', max_digits=12, null=True)),
                ('last_over_budget_at', models.DateTimeField(blank=True, help_text='超预算时间', null=True)),
            ],
            options={
                'verbose_name': '广告活动',
                'db_table': 'v1_ad_campaign',
            },
        ),
    ]
