# Generated by Django 5.1.2 on 2026-04-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0031_adcampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdRealtimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_id', models.CharField(help_text='活动ID主键', max_length=100, unique=True)),
                ('impressions', models.IntegerField(blank=True, help_text='曝光量', null=True)),
                ('impressions_percent', models.CharField(blank=True, help_text='曝光%', max_length=50, null=True)),
                ('clicks', models.IntegerField(blank=True, help_text='点击', null=True)),
                ('clicks_percent', models.CharField(blank=True, help_text='点击%', max_length=50, null=True)),
                ('ctr', models.CharField(blank=True, help_text='CTR', max_length=50, null=True)),
                ('cpc', models.CharField(blank=True, help_text='CPC', max_length=50, null=True)),
                ('spends', models.CharField(blank=True, help_text='花费', max_length=50, null=True)),
                ('spends_percent', models.CharField(blank=True, help_text='花费%', max_length=50, null=True)),
                ('cpa', models.CharField(blank=True, help_text='CPA', max_length=50, null=True)),
                ('sales', models.CharField(blank=True, help_text='广告销售额', max_length=50, null=True)),
                ('sales_percent', models.CharField(blank=True, help_text='广告销售额%', max_length=50, null=True)),
                ('direct_sales', models.CharField(blank=True, help_text='直接销售额', max_length=50, null=True)),
                ('acos', models.CharField(blank=True, help_text='ACoS', max_length=50, null=True)),
                ('roas', models.CharField(blank=True, help_text='ROAS', max_length=50, null=True)),
                ('orders', models.IntegerField(blank=True, help_text='广告订单', null=True)),
                ('direct_orders', models.IntegerField(blank=True, help_text='直接订单', null=True)),
                ('cvr', models.CharField(blank=True, help_text='CVR', max_length=50, null=True)),
                ('unit_price', models.CharField(blank=True, help_text='广告笔单价', max_length=50, null=True)),
                ('ad_units', models.IntegerField(blank=True, help_text='广告销量', null=True)),
                ('top_of_search_impression_share', models.CharField(blank=True, help_text='IS', max_length=50, null=True)),
            ],
            options={
                'verbose_name': '实时广告数据',
                'db_table': 'v1_ad_realtime_data',
            },
        ),
    ]
