# Generated by Django 5.1.2 on 2026-04-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0032_adrealtimedata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdRealtimeData',
            new_name='AdMetricData',
        ),
    ]
