# Generated by Django 5.1.2 on 2026-05-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0032_lx_campaign_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxAdPortfolios',
            fields=[
                ('portfolio_id', models.BigIntegerField(help_text='主键', primary_key=True, serialize=False)),
                ('profile_id', models.CharField(blank=True, help_text='店铺profile ID', max_length=100, null=True)),
                ('name', models.CharField(blank=True, help_text='名称', max_length=255, null=True)),
                ('budget', models.CharField(blank=True, help_text='预算', max_length=100, null=True)),
                ('in_budget', models.SmallIntegerField(blank=True, help_text='预算内外', null=True)),
                ('state', models.CharField(blank=True, help_text='状态', max_length=50, null=True)),
                ('budget_controls', models.TextField(blank=True, help_text='预算控制', null=True)),
                ('store_country', models.CharField(blank=True, help_text='国家代码', max_length=50, null=True)),
                ('store_name', models.CharField(blank=True, help_text='店铺名称', max_length=100, null=True)),
                ('store_type', models.CharField(blank=True, help_text='店铺类型', max_length=50, null=True)),
                ('store_id', models.CharField(blank=True, help_text='店铺ID', max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='系统更新时间')),
            ],
            options={
                'verbose_name': '广告组合表',
                'db_table': 'lx_ad_portfolios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxCampaignInfo',
            fields=[
                ('campaign_id', models.CharField(help_text='广告ID（主键）', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='广告名字', max_length=255)),
                ('state', models.CharField(help_text='有效状态', max_length=50)),
                ('sponsored_type', models.CharField(help_text='广告类型', max_length=50)),
                ('service_status', models.CharField(help_text='服务状态', max_length=50)),
                ('portfolio_id', models.CharField(blank=True, help_text='广告组合ID', max_length=100, null=True)),
                ('bidding_type', models.CharField(blank=True, help_text='竞价策略', max_length=50, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='预算', max_digits=12, null=True)),
                ('last_over_budget_at', models.DateTimeField(blank=True, help_text='超预算时间', null=True)),
                ('start_date', models.DateField(blank=True, help_text='开始日期', null=True)),
                ('tags', models.CharField(blank=True, help_text='标签', max_length=255, null=True)),
                ('profile_id', models.CharField(help_text='店铺profile ID', max_length=100)),
                ('store_id', models.CharField(help_text='店铺 ID', max_length=100)),
            ],
            options={
                'verbose_name': '广告活动基础表',
                'db_table': 'lx_campaign_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxCampaignMetrics',
            fields=[
                ('id', models.BigAutoField(help_text='主键', primary_key=True, serialize=False)),
                ('campaign_id', models.CharField(help_text='广告ID', max_length=100)),
                ('top_of_search_impression_share', models.CharField(blank=True, default='', help_text='搜索首位展示份额(IS)', max_length=50, null=True)),
                ('sales', models.DecimalField(decimal_places=2, default=0, help_text='广告销售额', max_digits=15)),
                ('direct_sales', models.DecimalField(decimal_places=2, default=0, help_text='直接销售额', max_digits=15)),
                ('orders', models.IntegerField(default=0, help_text='广告订单数')),
                ('direct_orders', models.IntegerField(default=0, help_text='直接订单数')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='广告笔单价', max_digits=10)),
                ('ad_units', models.IntegerField(default=0, help_text='广告销量')),
                ('impressions', models.IntegerField(default=0, help_text='曝光量')),
                ('clicks', models.IntegerField(default=0, help_text='点击次数')),
                ('cpc', models.DecimalField(decimal_places=2, default=0, help_text='CPC', max_digits=10)),
                ('spends', models.DecimalField(decimal_places=2, default=0, help_text='广告花费', max_digits=15)),
                ('timestamp', models.DateField(help_text='数据日期')),
                ('updated_at', models.DateTimeField(blank=True, help_text='系统更新时间', null=True)),
            ],
            options={
                'verbose_name': '广告活动指标表',
                'db_table': 'lx_campaign_metrics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxCurrencyRates',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, verbose_name='货币代码')),
                ('country_code', models.CharField(blank=True, default='', max_length=10, verbose_name='国家代码（主）')),
                ('country_code_alias', models.CharField(blank=True, default='', max_length=10, verbose_name='国家代码（别名）')),
                ('icon', models.CharField(blank=True, default='', max_length=20, verbose_name='货币符号')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='货币名称')),
                ('target_code', models.CharField(blank=True, default='', max_length=20, verbose_name='目标货币代码')),
                ('target_icon', models.CharField(blank=True, default='', max_length=20, verbose_name='目标货币符号')),
                ('rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='实际使用汇率（目标：人民币）')),
                ('is_cny', models.SmallIntegerField(default=0, verbose_name='是否人民币')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '货币汇率配置',
                'verbose_name_plural': '货币汇率配置',
                'db_table': 'lx_currency_rates',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AdCampaign',
        ),
        migrations.DeleteModel(
            name='AdMetricData',
        ),
        migrations.DeleteModel(
            name='LxCountryCode',
        ),
        migrations.DeleteModel(
            name='SalesProductListing',
        ),
        migrations.AlterModelOptions(
            name='lxshopprofile',
            options={'managed': False, 'verbose_name': '店铺Profiles', 'verbose_name_plural': '店铺Profiles'},
        ),
    ]
