# Generated by Django 5.1.2 on 2026-04-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0033_rename_adrealtimedata_admetricdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admetricdata',
            options={'verbose_name': '广告指标数据'},
        ),
        migrations.AlterModelTable(
            name='admetricdata',
            table='v1_ad_metric_data',
        ),
    ]
