# Generated by Django 5.1.2 on 2026-04-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0034_alter_admetricdata_options_alter_admetricdata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('profile_id', models.CharField(help_text='主键', max_length=64, primary_key=True, serialize=False)),
                ('alias', models.CharField(blank=True, help_text='别名', max_length=100, null=True)),
                ('country', models.CharField(blank=True, help_text='国家代码', max_length=10, null=True)),
                ('type', models.CharField(blank=True, help_text='类型', max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, help_text='创建时间', null=True)),
                ('local_date', models.DateField(blank=True, help_text='当地时间', null=True)),
                ('report_date', models.DateField(blank=True, help_text='报告时间', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='系统更新时间', null=True)),
            ],
            options={
                'verbose_name': '店铺资料',
                'verbose_name_plural': '店铺资料',
                'db_table': 'lx_shop_profiles',
                'managed': False,
            },
        ),
    ]
