# Generated by Django 5.1.2 on 2026-04-20 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0035_shopprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxListingInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='listing 产品ID')),
                ('msku', models.CharField(blank=True, default='', max_length=100)),
                ('fnsku', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('item_name', models.TextField(blank=True, null=True, verbose_name='标题')),
                ('fulfillment_channel_type', models.CharField(blank=True, default='', max_length=50, verbose_name='配送方式')),
                ('amz_product_id', models.CharField(blank=True, default='', max_length=100, verbose_name='商品编码')),
                ('amz_product_id_type', models.CharField(blank=True, default='', max_length=50)),
                ('parent_asin', models.CharField(blank=True, default='', max_length=100, verbose_name='父体ASIN')),
                ('variant_text', models.JSONField(blank=True, null=True, verbose_name='变体属性')),
                ('seller_category', models.TextField(blank=True, null=True, verbose_name='大类类目')),
                ('seller_rank', models.IntegerField(default=0, verbose_name='大类排名')),
                ('small_rank', models.IntegerField(default=0, verbose_name='小类排名')),
                ('small_category', models.CharField(blank=True, default='', max_length=255, verbose_name='小类类目')),
                ('stars', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='评分')),
                ('reviews_num', models.IntegerField(default=0, verbose_name='Rating总数')),
                ('pair_type', models.CharField(blank=True, default='', max_length=200, verbose_name='配对方式')),
                ('open_date_time', models.CharField(blank=True, default='', max_length=100, verbose_name='创建时间')),
                ('on_sale_time', models.CharField(blank=True, default='', max_length=100, verbose_name='开售时间')),
                ('first_order_time', models.CharField(blank=True, default='', max_length=100, verbose_name='首单时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Listing 基础表',
                'db_table': 'lx_listing_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxProductInfo',
            fields=[
                ('asin', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ASIN')),
                ('product_id', models.BigIntegerField(default=0, verbose_name='产品ID')),
                ('local_sku', models.CharField(blank=True, default='', max_length=100, verbose_name='本地SKU')),
                ('local_name', models.CharField(blank=True, default='', max_length=255, verbose_name='品名')),
                ('image', models.TextField(blank=True, null=True, verbose_name='图片')),
                ('brand', models.CharField(blank=True, default='', max_length=100, verbose_name='亚马逊品牌')),
                ('local_brand', models.CharField(blank=True, default='', max_length=100, verbose_name='本地品牌')),
                ('principal_list', models.JSONField(blank=True, null=True, verbose_name='负责人信息')),
                ('assort', models.CharField(blank=True, default='', max_length=100, verbose_name='分类')),
                ('label', models.CharField(blank=True, default='', max_length=100, verbose_name='标签')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '产品基础表',
                'db_table': 'lx_product_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxUserList',
            fields=[
                ('uid', models.BigIntegerField(help_text='主键', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='名字', max_length=255, null=True)),
                ('name_zh', models.CharField(blank=True, help_text='中文名字', max_length=255, null=True)),
                ('has_rule', models.BooleanField(blank=True, help_text='是否有规则', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='系统更新时间', null=True)),
            ],
            options={
                'verbose_name': '用户列表',
                'verbose_name_plural': '用户列表',
                'db_table': 'lx_user_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxListingMetrics',
            fields=[
                ('listing', models.OneToOneField(db_column='listing_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='metrics', serialize=False, to='api_v1.lxlistinginfo')),
                ('regular_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='售价')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='价格')),
                ('landed_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='优惠价')),
                ('b2b_price', models.CharField(blank=True, default='', max_length=255, verbose_name='B2B价格')),
                ('listing_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Listing价格')),
                ('afn_fulfillable_quantity', models.IntegerField(default=0, verbose_name='FBA可售')),
                ('fba_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='预估FBA费')),
                ('referral_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='平台费')),
                ('yesterday_volume', models.IntegerField(default=0, verbose_name='昨日销量')),
                ('total_volume', models.IntegerField(default=0, verbose_name='7天销量')),
                ('fourteen_volume', models.IntegerField(default=0, verbose_name='14天销量')),
                ('thirty_volume', models.IntegerField(default=0, verbose_name='30天销量')),
                ('average_seven_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='7天日均销量')),
                ('average_fourteen_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='14天日均销量')),
                ('average_thirty_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='30天日均销量')),
                ('yesterday_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='昨日销售额')),
                ('seven_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='7天销售额')),
                ('fourteen_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='14天销售额')),
                ('thirty_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='30天销售额')),
                ('yesterday_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='昨日广告费')),
                ('seven_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='7天广告费')),
                ('fourteen_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='14天广告费')),
                ('thirty_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='30天广告费')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Listing业务指标表',
                'db_table': 'lx_listing_metrics',
                'managed': False,
            },
        ),
    ]
