# Generated by Django 5.1.2 on 2026-04-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0036_lxlistinginfo_lxproductinfo_lxuserlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxSellers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_id', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('is_concept', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'lx_sellers',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ShopProfile',
        ),
    ]
