# Generated by Django 5.1.2 on 2026-04-20 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0037_lxsellers_delete_shopprofile'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='ProductClassification',
        # ),
        # migrations.DeleteModel(
        #     name='SalesProductListing',
        # ),
        # migrations.DeleteModel(
        #     name='SolarTermTag',
        # ),
    ]
