# Generated by Django 5.1.2 on 2026-04-20 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0038_delete_productclassification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxListingRemark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('remark_text', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('listing', models.OneToOneField(db_column='listing_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='remark', to='api_v1.lxlistinginfo')),
            ],
            options={
                'verbose_name': 'Listing备注',
                'verbose_name_plural': 'Listing备注',
                'db_table': 'lx_listing_remark',
            },
        ),
    ]
