# Generated by Django 5.1.2 on 2026-04-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0039_lxlistingremark'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxOrderProfit',
            fields=[
                ('listing_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='listing 产品ID')),
                ('report_date', models.DateField(verbose_name='报表时间')),
                ('asin', models.CharField(blank=True, default='', max_length=100, verbose_name='ASIN')),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='毛利润')),
                ('gross_margin', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='毛利率')),
                ('net_gross_margin', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='净毛利率')),
                ('volume', models.IntegerField(default=0, verbose_name='销量')),
                ('return_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='退货率')),
                ('refund_amount_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='退款率')),
                ('total_stock_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='仓储费')),
                ('spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='广告费')),
                ('spend_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='广告费率')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '产品利润报表',
                'verbose_name_plural': '产品利润报表',
                'db_table': 'lx_order_profit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyIcon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50, unique=True, verbose_name='国家(DE,FR等)')),
                ('code', models.CharField(max_length=50, verbose_name='货币代码(CNY,EUR等)')),
                ('icon', models.CharField(max_length=50, verbose_name='货币标识(￥,$等)')),
                ('name', models.CharField(max_length=100, verbose_name='名字(人民币,欧元等)')),
            ],
            options={
                'verbose_name': '货币图标配置',
                'verbose_name_plural': '货币图标配置',
                'db_table': 'currency_icon',
            },
        ),
    ]
