# Generated by Django 5.1.2 on 2026-05-13 08:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0039_lxlistingremark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LxAdGroupInfo',
            fields=[
                ('id', models.BigAutoField(help_text='自增主键', primary_key=True, serialize=False)),
                ('ad_group_id', models.CharField(help_text='广告组 ID', max_length=100)),
                ('name', models.CharField(default='', help_text='广告组名称', max_length=255)),
                ('state', models.CharField(default='', help_text='有效状态（enabled / paused / archived）', max_length=50)),
                ('service_status', models.CharField(default='', help_text='服务状态（平台层面）', max_length=100)),
                ('portfolio_id', models.CharField(blank=True, help_text='所属广告组合 ID', max_length=100, null=True)),
                ('default_bid', models.FloatField(blank=True, help_text='默认竞价金额', null=True)),
                ('count_product_ads', models.IntegerField(blank=True, help_text='关联商品广告数量', null=True)),
                ('campaign_id', models.CharField(default='', help_text='所属广告活动 ID', max_length=100)),
                ('profile_id', models.CharField(default='', help_text='店铺 Profile ID', max_length=100)),
                ('creation_date', models.CharField(blank=True, help_text='创建时间（原始字符串）', max_length=50, null=True)),
                ('updated_at', models.DateTimeField(blank=True, help_text='系统更新时间', null=True)),
            ],
            options={
                'verbose_name': '广告组基础信息表',
                'verbose_name_plural': '广告组基础信息表',
                'db_table': 'lx_ad_group_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxAdGroupMetrics',
            fields=[
                ('id', models.BigAutoField(help_text='自增主键', primary_key=True, serialize=False)),
                ('ad_group_id', models.CharField(help_text='广告组 ID', max_length=100)),
                ('campaign_id', models.CharField(help_text='所属广告活动 ID', max_length=100)),
                ('profile_id', models.CharField(help_text='店铺 Profile ID', max_length=100)),
                ('sales', models.FloatField(default=0, help_text='广告销售额')),
                ('direct_sales', models.FloatField(default=0, help_text='直接销售额')),
                ('orders', models.IntegerField(default=0, help_text='广告订单数')),
                ('direct_orders', models.IntegerField(default=0, help_text='直接订单数')),
                ('ad_units', models.IntegerField(default=0, help_text='广告销量（件数）')),
                ('impressions', models.IntegerField(default=0, help_text='曝光量')),
                ('clicks', models.IntegerField(default=0, help_text='点击次数')),
                ('cpc', models.FloatField(default=0, help_text='CPC（原始存储值，计算时以 spends/clicks 为准）')),
                ('spends', models.FloatField(default=0, help_text='广告花费')),
                ('timestamp', models.DateField(help_text='数据日期')),
                ('updated_at', models.DateTimeField(blank=True, help_text='系统更新时间', null=True)),
            ],
            options={
                'verbose_name': '广告组指标表',
                'verbose_name_plural': '广告组指标表',
                'db_table': 'lx_ad_group_metrics',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='workreport',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='今日工作内容'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='issues',
            field=models.TextField(blank=True, default='', verbose_name='遇到的问题 / 需要协助'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='plan',
            field=models.TextField(blank=True, default='', verbose_name='明日工作计划'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='完成进度（%）'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='汇报日期'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='type',
            field=models.CharField(choices=[('daily', '日报'), ('weekly', '周报')], default='daily', max_length=20, verbose_name='汇报类型'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reports', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='work_hours',
            field=models.DecimalField(decimal_places=1, default=8.0, max_digits=4, verbose_name='工时（小时）'),
        ),
    ]
