# Generated by Django 5.1.2 on 2026-05-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0034_fill_currency_icon'),
        ('api_v1', '0040_workreport_verbose_name_and_unmanaged_adgroup'),
    ]

    operations = [
    ]
