# Generated by Django 5.1.2 on 2026-04-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0040_lxorderprofit_currencyicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxShopProfile',
            fields=[
                ('profile_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='主键')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='别名')),
                ('country', models.CharField(blank=True, max_length=10, null=True, verbose_name='国家代码')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='类型')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('local_date', models.DateField(blank=True, null=True, verbose_name='当地时间')),
                ('report_date', models.DateField(blank=True, null=True, verbose_name='报告时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='系统更新时间')),
            ],
            options={
                'verbose_name': '店铺配置文件',
                'verbose_name_plural': '店铺配置文件',
                'db_table': 'lx_shop_profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxCountryCode',
            fields=[
                ('value', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='国家代码')),
                ('label', models.CharField(max_length=50, verbose_name='国家名称')),
            ],
            options={
                'verbose_name': '国家映射配置',
                'verbose_name_plural': '国家映射配置',
                'db_table': 'lx_country_codes',
            },
        ),
        migrations.AlterField(
            model_name='currencyicon',
            name='code',
            field=models.CharField(max_length=50, verbose_name='货币代码'),
        ),
        migrations.AlterField(
            model_name='currencyicon',
            name='country',
            field=models.CharField(max_length=50, unique=True, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='currencyicon',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='货币标识'),
        ),
        migrations.AlterField(
            model_name='currencyicon',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名字'),
        ),
    ]
