# Generated by Django 5.1.2 on 2026-04-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0029_salesproductlisting'),
        ('api_v1', '0041_lxshopprofile_lxcountrycode_alter_currencyicon_code_and_more'),
    ]

    operations = [
    ]
