# Generated by Django 5.1.2 on 2026-05-13 09:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0041_merge_20260513_1642'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageupload',
            options={'ordering': ('-created_at',), 'verbose_name': '图片上传记录', 'verbose_name_plural': '图片上传记录'},
        ),
        migrations.AlterModelOptions(
            name='lxadportfolios',
            options={'managed': False, 'verbose_name': '广告组合表', 'verbose_name_plural': '广告组合表'},
        ),
        migrations.AlterModelOptions(
            name='lxcampaigninfo',
            options={'managed': False, 'verbose_name': '广告活动基础表', 'verbose_name_plural': '广告活动基础表'},
        ),
        migrations.AlterModelOptions(
            name='lxcampaignmetrics',
            options={'managed': False, 'verbose_name': '广告活动指标表', 'verbose_name_plural': '广告活动指标表'},
        ),
        migrations.AlterModelOptions(
            name='lxlistinginfo',
            options={'managed': False, 'verbose_name': 'Listing 基础表', 'verbose_name_plural': 'Listing 基础表'},
        ),
        migrations.AlterModelOptions(
            name='lxlistingmetrics',
            options={'managed': False, 'verbose_name': 'Listing业务指标表', 'verbose_name_plural': 'Listing业务指标表'},
        ),
        migrations.AlterModelOptions(
            name='lxproductinfo',
            options={'managed': False, 'verbose_name': '产品基础表', 'verbose_name_plural': '产品基础表'},
        ),
        migrations.AlterModelOptions(
            name='lxsellers',
            options={'managed': False, 'verbose_name': '店铺', 'verbose_name_plural': '店铺'},
        ),
        migrations.AlterModelOptions(
            name='lxshopprofile',
            options={'managed': False, 'verbose_name': '店铺 Profiles', 'verbose_name_plural': '店铺 Profiles'},
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='access_expires_at',
            field=models.DateTimeField(verbose_name='访问令牌到期时间'),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='access_token',
            field=models.CharField(max_length=200, unique=True, verbose_name='访问令牌'),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='refresh_expires_at',
            field=models.DateTimeField(verbose_name='刷新令牌到期时间'),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='refresh_token',
            field=models.CharField(max_length=200, unique=True, verbose_name='刷新令牌'),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='revoked',
            field=models.BooleanField(default=False, verbose_name='是否已吊销'),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='cloudauthtoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到期时间'),
        ),
        migrations.AlterField(
            model_name='cloudauthtoken',
            name='site',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='云站点地址'),
        ),
        migrations.AlterField(
            model_name='cloudauthtoken',
            name='token',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='云 Token'),
        ),
        migrations.AlterField(
            model_name='cloudauthtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_token', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(max_length=100, unique=True, verbose_name='参数键'),
        ),
        migrations.AlterField(
            model_name='config',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='config',
            name='status',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.TextField(blank=True, default='', verbose_name='参数值'),
        ),
        migrations.AlterField(
            model_name='crawlercategory',
            name='category_id',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='类目 ID'),
        ),
        migrations.AlterField(
            model_name='crawlercategory',
            name='category_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='类目类型'),
        ),
        migrations.AlterField(
            model_name='crawlercategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='类目名称'),
        ),
        migrations.AlterField(
            model_name='crawlercategory',
            name='site',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='crawlercategory',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='crawlerconf',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='IP 地址'),
        ),
        migrations.AlterField(
            model_name='crawlerconf',
            name='node',
            field=models.CharField(max_length=200, verbose_name='节点标识'),
        ),
        migrations.AlterField(
            model_name='crawlerconf',
            name='order_num',
            field=models.IntegerField(default=0, verbose_name='排序号'),
        ),
        migrations.AlterField(
            model_name='crawlerconf',
            name='server_name',
            field=models.CharField(max_length=200, verbose_name='服务器名称'),
        ),
        migrations.AlterField(
            model_name='crawlerconf',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='crawlerlog',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='日志内容'),
        ),
        migrations.AlterField(
            model_name='crawlerlog',
            name='elapsed_ms',
            field=models.IntegerField(default=0, verbose_name='模块耗时（毫秒）'),
        ),
        migrations.AlterField(
            model_name='crawlerlog',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=45, verbose_name='请求 IP'),
        ),
        migrations.AlterField(
            model_name='crawlerlog',
            name='level',
            field=models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warn', 'Warn'), ('error', 'Error')], default='info', max_length=10, verbose_name='日志级别'),
        ),
        migrations.AlterField(
            model_name='crawlerlog',
            name='module',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='日志来源模块'),
        ),
        migrations.AlterField(
            model_name='crawlerlog',
            name='operator',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='crawlerlog',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='User-Agent'),
        ),
        migrations.AlterField(
            model_name='crawlerselleraccount',
            name='order_num',
            field=models.IntegerField(default=0, verbose_name='排序号'),
        ),
        migrations.AlterField(
            model_name='crawlerselleraccount',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='crawlerselleraccount',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='crawlerselleraccount',
            name='username',
            field=models.CharField(max_length=200, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='部门编号'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='department',
            name='order_num',
            field=models.IntegerField(default=0, verbose_name='排序号'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api_v1.department', verbose_name='父部门'),
        ),
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='dictitem',
            name='dict_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api_v1.dicttype', verbose_name='所属字典类型'),
        ),
        migrations.AlterField(
            model_name='dictitem',
            name='label',
            field=models.CharField(max_length=100, verbose_name='显示文本'),
        ),
        migrations.AlterField(
            model_name='dictitem',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='排序号'),
        ),
        migrations.AlterField(
            model_name='dictitem',
            name='status',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='dictitem',
            name='tag_type',
            field=models.CharField(blank=True, default='', help_text='Element Plus Tag type，用于前端渲染样式', max_length=20, verbose_name='标签样式'),
        ),
        migrations.AlterField(
            model_name='dictitem',
            name='value',
            field=models.CharField(max_length=100, verbose_name='实际值'),
        ),
        migrations.AlterField(
            model_name='dicttype',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='字典编码'),
        ),
        migrations.AlterField(
            model_name='dicttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='字典名称'),
        ),
        migrations.AlterField(
            model_name='dicttype',
            name='status',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='ext',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='扩展名'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='file_hash',
            field=models.CharField(db_index=True, help_text='用于秒传 / 断点续传判断', max_length=128, verbose_name='文件整体哈希'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='file_id',
            field=models.CharField(help_text='前端生成的文件 ID，与数据库主键区分', max_length=64, unique=True, verbose_name='文件 ID'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='api_v1.filefolder', verbose_name='所属文件夹'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='是否合并完成'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否逻辑删除'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='merge_file_id',
            field=models.CharField(help_text='分片阶段生成的临时合并 ID（pid），便于前端关联分片与目标文件', max_length=64, unique=True, verbose_name='合并文件 ID'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='MIME 类型'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='name',
            field=models.CharField(max_length=255, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='拥有者'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='size',
            field=models.BigIntegerField(default=0, verbose_name='文件大小（字节）'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='storage_path',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='存储路径'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='total_chunks',
            field=models.IntegerField(default=0, verbose_name='分片总数'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='uploaded_chunks',
            field=models.IntegerField(default=0, verbose_name='已上传分片数'),
        ),
        migrations.AlterField(
            model_name='filechunk',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api_v1.fileasset', verbose_name='所属文件'),
        ),
        migrations.AlterField(
            model_name='filechunk',
            name='chunk_hash',
            field=models.CharField(db_index=True, max_length=128, verbose_name='分片哈希'),
        ),
        migrations.AlterField(
            model_name='filechunk',
            name='num',
            field=models.IntegerField(help_text='从 0 开始', verbose_name='分片序号'),
        ),
        migrations.AlterField(
            model_name='filechunk',
            name='size',
            field=models.BigIntegerField(default=0, verbose_name='分片大小（字节）'),
        ),
        migrations.AlterField(
            model_name='filechunk',
            name='storage_path',
            field=models.CharField(max_length=255, verbose_name='存储相对路径'),
        ),
        migrations.AlterField(
            model_name='filechunk',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='filefolder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='filefolder',
            name='external_id',
            field=models.CharField(help_text='前端生成的文件夹 ID', max_length=64, unique=True, verbose_name='外部 ID'),
        ),
        migrations.AlterField(
            model_name='filefolder',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否逻辑删除'),
        ),
        migrations.AlterField(
            model_name='filefolder',
            name='name',
            field=models.CharField(max_length=255, verbose_name='文件夹名'),
        ),
        migrations.AlterField(
            model_name='filefolder',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='拥有者'),
        ),
        migrations.AlterField(
            model_name='filefolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api_v1.filefolder', verbose_name='父文件夹'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='cloud_path',
            field=models.CharField(blank=True, help_text='允许为空以便前端省略', max_length=500, null=True, verbose_name='Cloud 路径'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='图片 URL'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='status',
            field=models.CharField(blank=True, choices=[('normal', '正常'), ('warning', '警告'), ('error', '错误')], max_length=50, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='lxlistingremark',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='lxlistingremark',
            name='listing',
            field=models.OneToOneField(db_column='listing_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='remark', to='api_v1.lxlistinginfo', verbose_name='关联 Listing'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='component',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='前端组件路径'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='图标标识'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100, verbose_name='菜单名称'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='order_num',
            field=models.IntegerField(default=0, verbose_name='排序号'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api_v1.menu', verbose_name='父菜单'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='路由路径'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='perms',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='权限标识'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='route_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='路由名称 name'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.IntegerField(choices=[(1, '目录'), (2, '菜单'), (3, '按钮'), (4, '外链')], default=2, verbose_name='菜单类型'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='是否可见'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='level',
            field=models.CharField(choices=[('L', '低'), ('M', '中'), ('H', '高')], default='L', max_length=20, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='revoke_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='撤回时间'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('revoked', '已撤回')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='target_type',
            field=models.IntegerField(choices=[(1, '全体用户'), (2, '指定用户')], default=1, verbose_name='推送目标类型'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='type',
            field=models.CharField(blank=True, default='general', max_length=50, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='noticeread',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='api_v1.notice', verbose_name='关联公告'),
        ),
        migrations.AlterField(
            model_name='noticeread',
            name='read_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='读取时间'),
        ),
        migrations.AlterField(
            model_name='noticeread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_reads', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='noticetarget',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='api_v1.notice', verbose_name='关联公告'),
        ),
        migrations.AlterField(
            model_name='noticetarget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_targets', to=settings.AUTH_USER_MODEL, verbose_name='接收用户'),
        ),
        migrations.AlterField(
            model_name='operlog',
            name='action',
            field=models.TextField(verbose_name='操作描述'),
        ),
        migrations.AlterField(
            model_name='operlog',
            name='elapsed_ms',
            field=models.IntegerField(default=0, verbose_name='耗时（毫秒）'),
        ),
        migrations.AlterField(
            model_name='operlog',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=45, verbose_name='请求 IP'),
        ),
        migrations.AlterField(
            model_name='operlog',
            name='module',
            field=models.CharField(max_length=100, verbose_name='模块名称'),
        ),
        migrations.AlterField(
            model_name='operlog',
            name='operator',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='operlog',
            name='result',
            field=models.CharField(default='success', max_length=20, verbose_name='执行结果'),
        ),
        migrations.AlterField(
            model_name='operlog',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='User-Agent'),
        ),
        migrations.AlterField(
            model_name='orderprofitcache',
            name='data',
            field=models.TextField(blank=True, default='', verbose_name='响应 data 序列化字符串'),
        ),
        migrations.AlterField(
            model_name='orderprofitcache',
            name='key',
            field=models.CharField(db_index=True, help_text='基于请求参数的唯一 key（例如 sids,startDate,endDate,currency,searchValue 哈希）', max_length=128, unique=True, verbose_name='缓存唯一键'),
        ),
        migrations.AlterField(
            model_name='orderprofitcache',
            name='params',
            field=models.TextField(blank=True, default='', verbose_name='原始参数 JSON'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='角色编码'),
        ),
        migrations.AlterField(
            model_name='role',
            name='data_scope',
            field=models.IntegerField(choices=[(1, '全部数据'), (2, '部门及子部门数据'), (3, '本部门数据'), (4, '仅本人数据')], default=1, verbose_name='数据权限范围'),
        ),
        migrations.AlterField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(blank=True, related_name='roles', to='api_v1.menu', verbose_name='菜单列表'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, verbose_name='角色名称'),
        ),
        migrations.AlterField(
            model_name='role',
            name='order_num',
            field=models.IntegerField(default=0, verbose_name='排序号'),
        ),
        migrations.AlterField(
            model_name='role',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='role',
            name='status',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='头像地址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cloud_id',
            field=models.CharField(blank=True, default='', help_text='第三方 Seafile 返回的 account email/ID，后续同步删除使用', max_length=255, verbose_name='云账号标识'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.department', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(0, '保密'), (1, '男'), (2, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='api_v1.role', verbose_name='角色列表'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='dictitem',
            unique_together={('dict_type', 'value')},
        ),
    ]
