# Generated by Django 5.1.2 on 2026-05-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0042_model_style_refactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lxorderprofit',
            options={'managed': False, 'ordering': ['-report_date'], 'verbose_name': '产品利润报表', 'verbose_name_plural': '产品利润报表'},
        ),
    ]
