# Generated by Django 6.0.2 on 2026-05-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0044_lxadinfo_lxadmetrics_lxautotargetinginfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxAutoNegativeTargetingInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('target_id', models.CharField(max_length=100, verbose_name='否定定向 ID')),
                ('ad_group_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='所属广告组 ID')),
                ('portfolio_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='所属广告组合 ID')),
                ('campaign_id', models.CharField(max_length=100, verbose_name='所属广告活动 ID')),
                ('profile_id', models.CharField(max_length=100, verbose_name='店铺 Profile ID')),
                ('state', models.CharField(blank=True, help_text='enabled / archived', max_length=50, null=True, verbose_name='有效状态')),
                ('service_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='服务状态·平台层面')),
                ('exp_type', models.CharField(blank=True, help_text='asin / brand', max_length=50, null=True, verbose_name='否定类型')),
                ('exp_value', models.CharField(blank=True, help_text='ASIN 编码 或 品牌名称', max_length=200, null=True, verbose_name='否定值')),
                ('asin_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品售价')),
                ('asin_stars', models.CharField(blank=True, max_length=20, null=True, verbose_name='商品评分')),
                ('asin_review_count', models.CharField(blank=True, max_length=20, null=True, verbose_name='评论数量')),
                ('asin_title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='商品标题')),
                ('targeting_type', models.CharField(blank=True, help_text='auto', max_length=50, null=True, verbose_name='投放类型')),
                ('created_at', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '自动广告否定定向基础信息',
                'verbose_name_plural': '自动广告否定定向基础信息',
                'db_table': 'lx_auto_negative_targeting_info',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxAutoNegativeTargetingMetrics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('target_id', models.CharField(max_length=100, verbose_name='否定定向 ID')),
                ('campaign_id', models.CharField(max_length=100, verbose_name='所属广告活动 ID')),
                ('profile_id', models.CharField(max_length=100, verbose_name='店铺 Profile ID')),
                ('sales', models.CharField(blank=True, max_length=50, null=True, verbose_name='广告销售额')),
                ('orders', models.CharField(blank=True, max_length=50, null=True, verbose_name='广告订单数')),
                ('spends', models.CharField(blank=True, max_length=50, null=True, verbose_name='花费')),
                ('timestamp', models.DateField(verbose_name='数据日期')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '自动广告否定定向指标',
                'verbose_name_plural': '自动广告否定定向指标',
                'db_table': 'lx_auto_negative_targeting_metrics',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxNegativeKeywordInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('keyword_id', models.CharField(max_length=100, verbose_name='否定关键词 ID')),
                ('keyword_text', models.CharField(max_length=500, verbose_name='否定关键词文本')),
                ('match_type', models.CharField(help_text='negativeExact / negativePhrase', max_length=50, verbose_name='匹配方式')),
                ('portfolio_id', models.CharField(max_length=100, verbose_name='所属广告组合 ID')),
                ('campaign_id', models.CharField(max_length=100, verbose_name='所属广告活动 ID')),
                ('profile_id', models.CharField(max_length=100, verbose_name='店铺 Profile ID')),
                ('state', models.CharField(help_text='enabled / archived', max_length=50, verbose_name='有效状态')),
                ('service_status', models.CharField(max_length=100, verbose_name='服务状态·平台层面')),
                ('creation_date', models.CharField(max_length=50, verbose_name='创建时间')),
                ('targeting_mark', models.JSONField(blank=True, null=True, verbose_name='定向标记')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '否定关键词基础信息',
                'verbose_name_plural': '否定关键词基础信息',
                'db_table': 'lx_negative_keyword_info',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxNegativeKeywordMetrics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('keyword_id', models.CharField(max_length=100, verbose_name='否定关键词 ID')),
                ('campaign_id', models.CharField(max_length=100, verbose_name='所属广告活动 ID')),
                ('profile_id', models.CharField(max_length=100, verbose_name='店铺 Profile ID')),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='广告销售额')),
                ('orders', models.IntegerField(default=0, verbose_name='广告订单数')),
                ('spends', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='花费')),
                ('timestamp', models.DateField(verbose_name='数据日期')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '否定关键词指标',
                'verbose_name_plural': '否定关键词指标',
                'db_table': 'lx_negative_keyword_metrics',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
