# Generated by Django 5.1.2 on 2026-05-22 06:50
# Manually adjusted to resolve migration graph divergence:
# production had 0044_lxadinfo... and 0045_lxauto... applied before local 0044_phase1_nc_integration.
# All CreateModel ops for managed=False ad models are covered by those production migrations.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0044_phase1_nc_integration'),
        ('api_v1', '0045_lxautonegativetargetinginfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='menus',
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.TextField(blank=True, default='', help_text='PASSWORD 类型时存储 Fernet 密文，请勿直接修改', verbose_name='参数值'),
        ),
        migrations.AlterField(
            model_name='ncfileaccessrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ncfileaccessrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ncfileaccessrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ncgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ncgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ncgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ncsynctask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ncsynctask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ncsynctask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='CloudAuthToken',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]