# Generated by Django 5.1.2 on 2026-05-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0045_lxautonegativetargetinginfo_and_more'),
        ('api_v1', '0045_remove_role_model'),
    ]

    operations = [
    ]
