# Generated by Django 5.1.2 on 2026-05-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0046_ncgroup_folder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncsynctask',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('processing', '执行中'), ('success', '已成功'), ('failed', '已失败')], db_index=True, default='pending', max_length=15, verbose_name='任务状态'),
        ),
    ]
