# Generated by Django 5.1.2 on 2026-05-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0046_merge_20260522_1325'),
        ('api_v1', '0046_ncgroup_folder_id'),
    ]

    operations = [
    ]
