# Generated by Django 5.1.2 on 2026-05-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0047_add_processing_status_to_nc_sync_task'),
        ('api_v1', '0047_merge_0046_merge_20260522_1325_0046_ncgroup_folder_id'),
    ]

    operations = [
    ]
