# Generated by Django 5.1.2 on 2026-05-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0048_merge_20260522_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncsynctask',
            name='operation',
            field=models.CharField(choices=[('create_user', '创建 NC 用户'), ('update_user', '更新 NC 用户'), ('disable_user', '禁用 NC 用户'), ('enable_user', '启用 NC 用户'), ('add_to_group', '加入 NC 群组'), ('remove_from_group', '移出 NC 群组'), ('create_group', '创建 NC 群组'), ('delete_group', '删除 NC 群组'), ('set_admin', '设置 NC 管理员'), ('revoke_admin', '撤销 NC 管理员'), ('create_group_folder', '创建 Group Folder'), ('grant_group_folder', 'Group Folder 授权群组')], max_length=30, verbose_name='操作类型'),
        ),
    ]
