# Generated by Django 5.1.2 on 2026-05-23 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0049_alter_ncsynctask_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncfileaccessrule',
            name='nc_path',
            field=models.CharField(help_text="从 Group Folder 挂载点开始的子路径，如 '技术部/机密文档' 或 '技术部'；首尾斜杠自动忽略", max_length=500, verbose_name='NC 子路径'),
        ),
        migrations.AlterField(
            model_name='ncgroup',
            name='dept',
            field=models.ForeignKey(blank=True, help_text='DEPT/DEPT_ADMIN 类型时绑定对应部门；同一部门允许两条记录（DEPT + DEPT_ADMIN）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nc_groups', to='api_v1.department', verbose_name='关联部门'),
        ),
        migrations.AlterField(
            model_name='ncgroup',
            name='folder_id',
            field=models.IntegerField(blank=True, help_text='create_group_folder 返回的 folder id；DEPT_ADMIN 群组此字段为空，以对应 DEPT 群组的 folder_id 为准', null=True, verbose_name='NC Group Folder ID'),
        ),
        migrations.AlterField(
            model_name='ncgroup',
            name='group_type',
            field=models.CharField(choices=[('DEPT', '部门群组'), ('DEPT_ADMIN', '部门管理员群组'), ('COMPANY_SHARED', '公司共享群组'), ('CUSTOM', '自定义群组')], default='CUSTOM', max_length=20, verbose_name='群组类型'),
        ),
        migrations.AlterField(
            model_name='ncsynctask',
            name='operation',
            field=models.CharField(choices=[('create_user', '创建 NC 用户'), ('update_user', '更新 NC 用户'), ('disable_user', '禁用 NC 用户'), ('enable_user', '启用 NC 用户'), ('add_to_group', '加入 NC 群组'), ('remove_from_group', '移出 NC 群组'), ('create_group', '创建 NC 群组'), ('delete_group', '删除 NC 群组'), ('set_admin', '设置 NC 管理员'), ('revoke_admin', '撤销 NC 管理员'), ('create_group_folder', '创建 Group Folder'), ('grant_group_folder', 'Group Folder 授权群组'), ('enable_folder_acl', '开启文件夹 ACL 模式'), ('set_path_acl', '设置子目录 ACL 规则')], max_length=30, verbose_name='操作类型'),
        ),
        migrations.AlterUniqueTogether(
            name='ncgroup',
            unique_together={('dept', 'group_type')},
        ),
    ]
