# Generated by Django 5.1.2 on 2026-05-23 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0055_seed_nc_folder_perm_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='api_v1.department', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_builtin',
            field=models.BooleanField(default=False, help_text='内置岗位不可删除，如 sys_admin', verbose_name='是否内置'),
        ),
    ]
