# Generated by Django 5.1.2 on 2026-05-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0066_merge_20260529'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxShops',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False, verbose_name='店铺 ID')),
                ('mid', models.IntegerField(blank=True, null=True, verbose_name='Marketplace 序号')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='店铺名称')),
                ('seller_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seller ID')),
                ('account_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='账号名称')),
                ('seller_account_id', models.IntegerField(blank=True, null=True, verbose_name='卖家账号 ID')),
                ('region', models.CharField(blank=True, max_length=20, null=True, verbose_name='大区（如 EU / NA）')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='国家')),
                ('has_ads_setting', models.IntegerField(choices=[(0, '未配置'), (1, '已配置')], default=0, verbose_name='是否配置广告设置')),
                ('marketplace_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Marketplace ID')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='店铺状态')),
            ],
            options={
                'verbose_name': '店铺基础数据',
                'verbose_name_plural': '店铺基础数据',
                'db_table': 'lx_shops',
                'ordering': ['sid'],
                'managed': False,
            },
        ),
    ]
