# Generated by Django 5.1.2 on 2026-06-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0068_add_lx_listing_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxUser',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户 ID')),
                ('realname', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户名')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('login_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='登录次数')),
                ('last_login_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='最近登录时间')),
                ('last_login_ip', models.CharField(blank=True, max_length=45, null=True, verbose_name='最近登录 IP')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '正常')], default=1, verbose_name='状态')),
                ('create_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='创建时间')),
                ('role', models.TextField(blank=True, null=True, verbose_name='角色（逗号分隔）')),
                ('seller', models.TextField(blank=True, null=True, verbose_name='店铺权限（逗号分隔）')),
                ('is_master', models.IntegerField(choices=[(0, '子账号'), (1, '主账号')], default=0, verbose_name='是否主账号')),
            ],
            options={
                'verbose_name': '领星用户',
                'verbose_name_plural': '领星用户',
                'db_table': 'lx_user',
                'ordering': ['uid'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxTimePricingStrategy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('shops', models.JSONField(default=list, help_text='店铺标识列表，如 ["US", "UK"]', verbose_name='适用店铺')),
                ('status', models.IntegerField(choices=[(0, '暂停'), (1, '开启')], default=1, verbose_name='模板状态')),
                ('start_time', models.BigIntegerField(blank=True, help_text='null 表示不限', null=True, verbose_name='模板开始时间（毫秒时间戳）')),
                ('end_time', models.BigIntegerField(blank=True, help_text='null 表示不限', null=True, verbose_name='模板结束时间（毫秒时间戳）')),
                ('base_value_type', models.IntegerField(choices=[(1, '应用策略时的值'), (2, '固定值')], default=1, verbose_name='基准值类型')),
                ('base_fixed_value', models.DecimalField(blank=True, decimal_places=4, help_text='仅当基准值类型为固定值时使用', max_digits=12, null=True, verbose_name='固定基准值')),
                ('field_settings', models.JSONField(default=dict, help_text='JSON 对象，包含 categories（归类列表）、managers（负责人列表）、tags（标签列表）', verbose_name='字段设置')),
                ('time_mode', models.CharField(default='byDay', help_text='byDay：按天 / byWeek：按周 / calendar：日历模式', max_length=20, verbose_name='分时模式')),
                ('time_settings', models.JSONField(default=dict, help_text='时间段配置（segments）或日历网格（grid），结构由 time_mode 决定', verbose_name='分时设置')),
                ('callback_settings', models.JSONField(default=dict, help_text='失效回调配置：type + multiplier/fixed 值', verbose_name='回调策略')),
                ('weight', models.IntegerField(default=1, help_text='优先级排序，数值越大优先级越高', verbose_name='权重')),
                ('execution_result', models.IntegerField(choices=[(1, '通知'), (2, '不通知')], default=2, verbose_name='执行结果通知')),
                ('type', models.CharField(choices=[('bidding_time', '竞价分时')], default='bidding_time', max_length=50, verbose_name='策略类型')),
                ('creator', models.CharField(default='', help_text='创建该策略的用户名', max_length=100, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分时调价策略',
                'verbose_name_plural': '分时调价策略',
                'db_table': 'lx_time_pricing_strategy',
                'ordering': ['-weight', '-created_at'],
            },
        ),
    ]
