# Generated by Django 5.1.2 on 2026-06-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0069_add_time_pricing_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxUser',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户 ID')),
                ('realname', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户名')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('login_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='登录次数')),
                ('last_login_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='最近登录时间')),
                ('last_login_ip', models.CharField(blank=True, max_length=45, null=True, verbose_name='最近登录 IP')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '正常')], default=1, verbose_name='状态')),
                ('create_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='创建时间')),
                ('role', models.TextField(blank=True, null=True, verbose_name='角色（逗号分隔）')),
                ('seller', models.TextField(blank=True, null=True, verbose_name='店铺权限（逗号分隔）')),
                ('is_master', models.IntegerField(choices=[(0, '子账号'), (1, '主账号')], default=0, verbose_name='是否主账号')),
            ],
            options={
                'verbose_name': '领星用户',
                'verbose_name_plural': '领星用户',
                'db_table': 'lx_user',
                'ordering': ['uid'],
                'managed': False,
            },
        ),
    ]
