# Generated by Django 5.1.2 on 2026-06-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0069_add_time_pricing_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxSpCampaignReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('targeting_type', models.CharField(default='', max_length=20, verbose_name='投放类型')),
                ('impressions', models.IntegerField(default=0, verbose_name='展示量')),
                ('clicks', models.IntegerField(default=0, verbose_name='点击量')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='花费')),
                ('report_date', models.DateField(verbose_name='报表日期')),
                ('profile_id', models.BigIntegerField(verbose_name='亚马逊店铺数字 ID')),
                ('campaign_id', models.BigIntegerField(verbose_name='广告活动 ID')),
                ('same_orders', models.IntegerField(default=0, verbose_name='直接成交订单数')),
                ('orders', models.IntegerField(default=0, verbose_name='订单数')),
                ('same_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='直接成交销售额')),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='销售额')),
                ('units', models.IntegerField(default=0, verbose_name='销量')),
                ('same_units', models.IntegerField(default=0, verbose_name='直接成交量')),
            ],
            options={
                'verbose_name': 'SP 广告活动报表',
                'verbose_name_plural': 'SP 广告活动报表',
                'db_table': 'lx_sp_campaign_report',
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['campaign_id', 'profile_id'], name='lx_sp_campa_campaig_e8a468_idx'), models.Index(fields=['report_date'], name='lx_sp_campa_report__19c318_idx')],
                'unique_together': {('campaign_id', 'profile_id', 'report_date')},
            },
        ),
    ]
