# Generated by Django 5.1.2 on 2026-06-02 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0067_lxshops'),
        ('api_v1', '0070_lxuser'),
    ]

    operations = [
    ]
