# Generated by Django 5.1.2 on 2026-06-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0072_add_lx_sp_ad_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxSpKeywordReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('keyword_id', models.BigIntegerField(verbose_name='关键词 ID')),
                ('match_type', models.CharField(default='', max_length=20, verbose_name='匹配类型')),
                ('keyword_text', models.CharField(default='', max_length=500, verbose_name='关键词')),
                ('ad_group_id', models.BigIntegerField(verbose_name='广告组 ID')),
                ('campaign_id', models.BigIntegerField(verbose_name='广告活动 ID')),
                ('profile_id', models.BigIntegerField(verbose_name='亚马逊店铺数字 ID')),
                ('impressions', models.IntegerField(default=0, verbose_name='展示量')),
                ('clicks', models.IntegerField(default=0, verbose_name='点击量')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='花费')),
                ('report_date', models.DateField(verbose_name='报表日期')),
                ('same_orders', models.IntegerField(default=0, verbose_name='直接成交订单数')),
                ('orders', models.IntegerField(default=0, verbose_name='订单数')),
                ('same_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='直接成交销售额')),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='销售额')),
                ('units', models.IntegerField(default=0, verbose_name='销量')),
                ('same_units', models.IntegerField(default=0, verbose_name='直接成交销量')),
            ],
            options={
                'verbose_name': 'SP 关键词报表',
                'verbose_name_plural': 'SP 关键词报表',
                'db_table': 'lx_sp_keyword_report',
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['campaign_id', 'profile_id'], name='lx_sp_keywo_campaig_1392d3_idx'), models.Index(fields=['ad_group_id'], name='lx_sp_keywo_ad_grou_6f68fc_idx'), models.Index(fields=['keyword_id'], name='lx_sp_keywo_keyword_e28a81_idx'), models.Index(fields=['report_date'], name='lx_sp_keywo_report__a6e162_idx')],
                'unique_together': {('keyword_id', 'profile_id', 'report_date')},
            },
        ),
    ]
