# Generated by Django 5.1.2 on 2026-06-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0073_add_lx_sp_keyword_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxSpTargetReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('target_id', models.BigIntegerField(verbose_name='投放 ID')),
                ('targeting_type', models.CharField(default='', max_length=50, verbose_name='投放类别')),
                ('targeting_expression', models.CharField(default='', max_length=100, verbose_name='投放表达式')),
                ('ad_group_id', models.BigIntegerField(verbose_name='广告组 ID')),
                ('campaign_id', models.BigIntegerField(verbose_name='广告活动 ID')),
                ('profile_id', models.BigIntegerField(verbose_name='亚马逊店铺数字 ID')),
                ('impressions', models.IntegerField(default=0, verbose_name='展示量')),
                ('clicks', models.IntegerField(default=0, verbose_name='点击量')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='花费')),
                ('report_date', models.DateField(verbose_name='报表日期')),
                ('same_orders', models.IntegerField(default=0, verbose_name='直接成交订单数')),
                ('orders', models.IntegerField(default=0, verbose_name='订单数')),
                ('same_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='直接成交销售额')),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='销售额')),
                ('units', models.IntegerField(default=0, verbose_name='销量')),
                ('same_units', models.IntegerField(default=0, verbose_name='直接成交销量')),
            ],
            options={
                'verbose_name': 'SP 商品定位报表',
                'verbose_name_plural': 'SP 商品定位报表',
                'db_table': 'lx_sp_target_report',
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['campaign_id', 'profile_id'], name='lx_sp_targe_campaig_8da5e6_idx'), models.Index(fields=['ad_group_id'], name='lx_sp_targe_ad_grou_9eaf1f_idx'), models.Index(fields=['target_id'], name='lx_sp_targe_target__d244d8_idx'), models.Index(fields=['report_date'], name='lx_sp_targe_report__b9a062_idx')],
                'unique_together': {('target_id', 'profile_id', 'report_date')},
            },
        ),
    ]
