# Generated by Django 5.1.2 on 2026-06-04 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0071_merge_0067_lxshops_0070_lxuser'),
        ('api_v1', '0074_add_lx_sp_target_report'),
    ]

    operations = [
    ]
