# Generated by Django 5.1.2 on 2026-06-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0074_add_lx_sp_target_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', help_text='形如 2021-08', max_length=10, verbose_name='汇率年月')),
                ('code', models.CharField(default='', max_length=10, verbose_name='币种')),
                ('icon', models.CharField(default='', max_length=10, verbose_name='币种符号')),
                ('name', models.CharField(default='', max_length=50, verbose_name='币种名')),
                ('rate_org', models.CharField(default='1.0000', help_text='数据来源于中国银行官方汇率', max_length=20, verbose_name='官方汇率')),
                ('my_rate', models.CharField(default='1.0000', help_text='用户自定义汇率，系统优先使用该汇率数据', max_length=20, verbose_name='我的汇率')),
                ('update_time', models.CharField(default='', max_length=30, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '汇率',
                'verbose_name_plural': '汇率列表',
                'db_table': 'lx_exchange_rate',
                'ordering': ['-date'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='lxtimepricingstrategy',
            options={'ordering': ['weight', '-created_at'], 'verbose_name': '分时调价策略', 'verbose_name_plural': '分时调价策略'},
        ),
        migrations.AlterField(
            model_name='lxtimepricingstrategy',
            name='weight',
            field=models.IntegerField(default=1, help_text='优先级排序，数值越小优先级越高', verbose_name='权重'),
        ),
    ]
