# Generated by Django 5.1.2 on 2026-06-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0075_lx_exchange_rate'),
        ('api_v1', '0075_merge_20260604_1011'),
    ]

    operations = [
    ]
