# Generated by Django 5.1.2 on 2026-06-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0075_lx_exchange_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxAdRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '暂停')], default='active', max_length=20, verbose_name='规则状态')),
                ('shops', models.JSONField(default=list, help_text='店铺 profile_id 列表，如 [123, 456]', verbose_name='适用店铺')),
                ('effective_type', models.CharField(choices=[('within_days', '指定天数内'), ('beyond_days', '指定天数之外'), ('date_range', '日期范围')], default='within_days', max_length=30, verbose_name='生效周期类型')),
                ('effective_days', models.IntegerField(blank=True, help_text='effective_type 为 within_days/beyond_days 时使用', null=True, verbose_name='生效天数')),
                ('effective_start_month', models.IntegerField(blank=True, help_text='effective_type 为 date_range 时使用，1-12', null=True, verbose_name='生效起始月')),
                ('effective_start_day', models.IntegerField(blank=True, help_text='effective_type 为 date_range 时使用，1-31', null=True, verbose_name='生效起始日')),
                ('effective_end_month', models.IntegerField(blank=True, help_text='effective_type 为 date_range 时使用，1-12', null=True, verbose_name='生效结束月')),
                ('effective_end_day', models.IntegerField(blank=True, help_text='effective_type 为 date_range 时使用，1-31', null=True, verbose_name='生效结束日')),
                ('categories', models.JSONField(default=list, verbose_name='归类列表')),
                ('unlimited_categories', models.BooleanField(default=False, verbose_name='归类不限')),
                ('managers', models.JSONField(default=list, verbose_name='负责人列表')),
                ('unlimited_managers', models.BooleanField(default=False, verbose_name='负责人不限')),
                ('tags', models.JSONField(default=list, verbose_name='标签列表')),
                ('unlimited_tags', models.BooleanField(default=False, verbose_name='标签不限')),
                ('comparison_target', models.CharField(choices=[('campaign', '广告活动'), ('ad_group', '广告组'), ('search_terms', '用户搜索词'), ('targeting', '投放')], max_length=50, verbose_name='比对对象')),
                ('comparison_multi_targets', models.JSONField(default=list, help_text='当 comparison_target 为 targeting 时，可多选 targeting / keyword / product_targeting', verbose_name='投放多选列表')),
                ('condition_sets', models.JSONField(default=list, help_text='JSON 数组：每个元素包含 days（天数）和 conditions（条件列表）', verbose_name='条件组')),
                ('linked_time_rules', models.JSONField(default=list, help_text='分时规则 ID 列表，命中后规则才生效', verbose_name='关联分时规则')),
                ('linked_time_rules_exclude', models.JSONField(default=list, help_text='分时规则 ID 列表，命中后规则不生效', verbose_name='排除分时规则')),
                ('bid_action', models.JSONField(default=dict, help_text='{"type": "...", "value": 0, "limit": null}', verbose_name='竞价操作')),
                ('budget_action', models.JSONField(default=dict, help_text='{"type": "...", "value": 0, "limit": null}', verbose_name='预算操作')),
                ('negative_action', models.CharField(blank=True, default='', help_text='仅 comparison_target 为 search_terms 时有效', max_length=50, verbose_name='否定操作')),
                ('add_keyword_action', models.CharField(blank=True, default='', help_text='仅 comparison_target 为 search_terms 时有效', max_length=50, verbose_name='关键词投放操作')),
                ('add_keyword_match_type', models.CharField(choices=[('broad', '广泛匹配'), ('phrase', '词组匹配'), ('exact', '精准匹配')], default='broad', max_length=20, verbose_name='关键词匹配方式')),
                ('add_keyword_bid_type', models.CharField(choices=[('actual_cpc', '采用实际出单 CPC'), ('fixed', '填写固定值')], default='actual_cpc', max_length=20, verbose_name='关键词竞价方式')),
                ('add_keyword_max_bid', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='最高竞价')),
                ('add_keyword_fixed_bid', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='固定竞价')),
                ('creator', models.CharField(default='', help_text='创建该规则的用户名', max_length=100, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '广告规则',
                'verbose_name_plural': '广告规则',
                'db_table': 'lx_ad_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LxAdRuleGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('name', models.CharField(max_length=100, verbose_name='规则组名称')),
                ('execution_cycle', models.IntegerField(default=1, help_text='每 N 天执行一次，默认 1 表示每天执行', verbose_name='执行周期（天）')),
                ('rule_order', models.JSONField(default=list, help_text='规则 ID 数组，如 [3, 7, 1]，按序执行', verbose_name='规则 ID 有序列表')),
                ('creator', models.CharField(default='', help_text='创建该规则组的用户名', max_length=100, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '规则组',
                'verbose_name_plural': '规则组',
                'db_table': 'lx_ad_rule_group',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CurrencyIcon',
        ),
        migrations.DeleteModel(
            name='LxAdGroupInfo',
        ),
        migrations.DeleteModel(
            name='LxAdGroupMetrics',
        ),
        migrations.DeleteModel(
            name='LxAdInfo',
        ),
        migrations.DeleteModel(
            name='LxAdMetrics',
        ),
        migrations.DeleteModel(
            name='LxAdPortfolios',
        ),
        migrations.DeleteModel(
            name='LxAutoNegativeTargetingInfo',
        ),
        migrations.DeleteModel(
            name='LxAutoNegativeTargetingMetrics',
        ),
        migrations.DeleteModel(
            name='LxAutoTargetingInfo',
        ),
        migrations.DeleteModel(
            name='LxAutoTargetingMetrics',
        ),
        migrations.DeleteModel(
            name='LxCampaignInfo',
        ),
        migrations.DeleteModel(
            name='LxCampaignMetrics',
        ),
        migrations.DeleteModel(
            name='LxCurrencyRates',
        ),
        migrations.DeleteModel(
            name='LxNegativeKeywordInfo',
        ),
        migrations.DeleteModel(
            name='LxNegativeKeywordMetrics',
        ),
        migrations.DeleteModel(
            name='LxShopProfile',
        ),
    ]
