# Generated by Django 5.1.2 on 2026-06-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0076_merge_0075_lx_exchange_rate_0075_merge_20260604_1011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyIcon',
        ),
        migrations.DeleteModel(
            name='LxAdGroupInfo',
        ),
        migrations.DeleteModel(
            name='LxAdGroupMetrics',
        ),
        migrations.DeleteModel(
            name='LxAdInfo',
        ),
        migrations.DeleteModel(
            name='LxAdMetrics',
        ),
        migrations.DeleteModel(
            name='LxAdPortfolios',
        ),
        migrations.DeleteModel(
            name='LxAutoNegativeTargetingInfo',
        ),
        migrations.DeleteModel(
            name='LxAutoNegativeTargetingMetrics',
        ),
        migrations.DeleteModel(
            name='LxAutoTargetingInfo',
        ),
        migrations.DeleteModel(
            name='LxAutoTargetingMetrics',
        ),
        migrations.DeleteModel(
            name='LxCampaignInfo',
        ),
        migrations.DeleteModel(
            name='LxCampaignMetrics',
        ),
        migrations.DeleteModel(
            name='LxCurrencyRates',
        ),
        migrations.DeleteModel(
            name='LxNegativeKeywordInfo',
        ),
        migrations.DeleteModel(
            name='LxNegativeKeywordMetrics',
        ),
        migrations.DeleteModel(
            name='LxShopProfile',
        ),
    ]
