# Generated by Django 5.1.2 on 2026-06-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0078_lxadrule_lxadrulegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lxadrule',
            name='effective_days',
        ),
        migrations.AddField(
            model_name='lxadrule',
            name='effective_days_end',
            field=models.IntegerField(blank=True, help_text='effective_type 为 within_days/beyond_days 时使用，范围终点', null=True, verbose_name='生效天数结束'),
        ),
        migrations.AddField(
            model_name='lxadrule',
            name='effective_days_start',
            field=models.IntegerField(blank=True, help_text='effective_type 为 within_days/beyond_days 时使用，范围起点', null=True, verbose_name='生效天数起始'),
        ),
    ]
