# Generated by Django 5.1.2 on 2026-06-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0079_remove_lxadrule_effective_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lxadrule',
            name='other_action',
            field=models.JSONField(default=dict, help_text='{"type": "pause"|"archive"|"", "notify": true}', verbose_name='其他操作'),
        ),
    ]
