# Generated by Django 5.1.2 on 2026-06-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0080_lxadrule_other_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='lxadrule',
            name='ad_type',
            field=models.CharField(default='all', help_text='all：不限 / manual：手动 / auto：自动', max_length=20, verbose_name='广告类型'),
        ),
        migrations.AddField(
            model_name='lxadrule',
            name='auto_targeting_groups',
            field=models.JSONField(default=list, help_text='同类商品/紧密匹配/关联商品/宽泛匹配', verbose_name='自动定位组'),
        ),
        migrations.AddField(
            model_name='lxadrule',
            name='targeting_bid_actions',
            field=models.JSONField(default=list, help_text='Campaign AUTO/MANUAL 专属，每条包含 targetingGroups/conditionSets/bidAction', verbose_name='投放竞价操作列表'),
        ),
        migrations.AddField(
            model_name='lxadrule',
            name='unlimited_auto_targeting',
            field=models.BooleanField(default=False, verbose_name='自动定位组不限'),
        ),
    ]
