# Generated by Django 5.1.2 on 2026-06-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0081_lxadrule_ad_type_lxadrule_auto_targeting_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lxadrule',
            name='ad_type',
            field=models.CharField(blank=True, default='all', help_text='all：不限 / manual：手动 / auto：自动', max_length=20, verbose_name='广告类型'),
        ),
    ]
