# Generated by Django 5.1.2 on 2026-06-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0082_alter_lxadrule_ad_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lxadrulegroup',
            name='weight',
            field=models.IntegerField(default=0, help_text='数值越低优先级越高，默认 0 表示最高优先级', verbose_name='权重'),
        ),
    ]
