# Generated by Django 5.1.2 on 2026-06-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0083_lxadrulegroup_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lxadrule',
            name='comparison_target',
            field=models.CharField(choices=[('campaign', '广告活动'), ('ad_group', '广告组'), ('search_terms', '用户搜索词'), ('targeting', '投放'), ('negative_targeting', '否定投放')], max_length=50, verbose_name='比对对象'),
        ),
        migrations.AlterField(
            model_name='lxadrule',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='规则名称'),
        ),
    ]
