# Generated by Django 5.1.2 on 2026-06-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0084_alter_lxadrule_comparison_target_alter_lxadrule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lxadrule',
            name='comparison_target',
            field=models.CharField(choices=[('campaign', '广告活动'), ('ad_group', '广告组'), ('search_terms', '用户搜索词'), ('targeting', '投放'), ('negative_targeting', '否定投放'), ('keyword', '关键词'), ('product_targeting', '商品投放')], max_length=50, verbose_name='比对对象'),
        ),
    ]
