# Generated by Django 5.1.2 on 2026-06-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0085_alter_lxadrule_comparison_target'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LxUserList',
        ),
    ]
