# Generated by Django 5.1.2 on 2026-06-15 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0086_delete_lxuserlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxListingMeta',
            fields=[
                ('listing_data', models.OneToOneField(db_column='listing_data_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='meta', serialize=False, to='api_v1.lxlistingdata', verbose_name='关联 Listing 数据')),
                ('remark_text', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('assort', models.CharField(blank=True, default='', max_length=100, verbose_name='分类')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Listing 通用元数据',
                'verbose_name_plural': 'Listing 通用元数据列表',
                'db_table': 'lx_listing_meta',
                'ordering': ['-updated_at'],
            },
        ),
    ]
