# Generated by Django 5.1.2 on 2026-06-15 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0087_lxlistingmeta_delete_lxsellers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxLocalProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('cid', models.IntegerField(verbose_name='类别 ID')),
                ('category_name', models.CharField(default='', max_length=100, verbose_name='类别名称')),
                ('bid', models.IntegerField(verbose_name='品牌 ID')),
                ('brand_name', models.CharField(default='', max_length=100, verbose_name='品牌名称')),
                ('sku', models.CharField(default='', max_length=200, verbose_name='本地产品 SKU')),
                ('sku_identifier', models.CharField(default='', max_length=200, verbose_name='SKU 识别码')),
                ('product_name', models.CharField(default='', max_length=255, verbose_name='品名')),
                ('pic_url', models.CharField(default='', max_length=512, verbose_name='图片链接')),
                ('ps_id', models.IntegerField(verbose_name='SPU 唯一 ID')),
                ('spu', models.CharField(default='', max_length=100, verbose_name='SPU')),
                ('cg_delivery', models.IntegerField(verbose_name='采购交期（天）')),
                ('cg_transport_costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='采购运输成本')),
                ('purchase_remark', models.TextField(blank=True, default='', verbose_name='采购备注')),
                ('cg_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='采购成本（人民币）')),
                ('cg_opt_uid', models.CharField(blank=True, default='', max_length=50, verbose_name='采购员 UID')),
                ('cg_opt_username', models.CharField(blank=True, default='', max_length=100, verbose_name='采购员名称')),
                ('open_status', models.IntegerField(choices=[(0, '停用'), (1, '启用')], default=1, verbose_name='产品启用状态')),
                ('status', models.IntegerField(choices=[(0, '停售'), (1, '在售'), (2, '开发中'), (3, '清仓')], default=1, verbose_name='产品状态')),
                ('status_text', models.CharField(default='', max_length=50, verbose_name='状态文本')),
                ('is_combo', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否为组合产品')),
                ('product_developer_uid', models.CharField(blank=True, default='', max_length=50, verbose_name='开发人员 UID')),
                ('product_developer', models.CharField(blank=True, default='', max_length=100, verbose_name='开发人员名称')),
                ('attribute', models.JSONField(blank=True, help_text='数组，元素格式：{attr_id, attr_name, attr_value}', null=True, verbose_name='产品属性')),
                ('tag_ids', models.JSONField(blank=True, help_text='产品关联的标签 ID 数组，如 ["907204347399528686"]', null=True, verbose_name='标签 ID 列表')),
                ('supplier_quote_ids', models.JSONField(blank=True, help_text='产品关联的供应商报价 psq_id 数组，如 ["psq_001", "psq_002"]', null=True, verbose_name='供应商报价 ID 列表')),
                ('custom_field_ids', models.JSONField(blank=True, help_text='产品关联的自定义字段 field_id 数组，如 ["field_001"]', null=True, verbose_name='自定义字段 ID 列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '本地产品',
                'verbose_name_plural': '本地产品列表',
                'db_table': 'lx_local_product',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LxProductCustomField',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('field_id', models.CharField(default='', max_length=50, verbose_name='字段 ID')),
                ('field_name', models.CharField(default='', max_length=100, verbose_name='字段名称')),
                ('val_text', models.TextField(blank=True, default='', verbose_name='字段值')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='api_v1.lxlocalproduct', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': '产品自定义字段',
                'verbose_name_plural': '产品自定义字段列表',
                'db_table': 'lx_product_custom_field',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LxProductTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('global_tag_id', models.CharField(default='', max_length=50, verbose_name='标签 ID')),
                ('tag_name', models.CharField(default='', max_length=100, verbose_name='标签名称')),
                ('color', models.CharField(default='', max_length=20, verbose_name='标签颜色')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api_v1.lxlocalproduct', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': '产品标签',
                'verbose_name_plural': '产品标签列表',
                'db_table': 'lx_product_tag',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LxSupplierQuote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('psq_id', models.CharField(blank=True, default='', max_length=50, verbose_name='供应商报价 ID')),
                ('supplier_id', models.IntegerField(blank=True, null=True, verbose_name='供应商 ID')),
                ('is_primary', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否为首选供应商')),
                ('supplier_product_url', models.JSONField(blank=True, help_text='字符串数组，每个元素为一个采购 URL', null=True, verbose_name='采购链接')),
                ('quote_remark', models.TextField(blank=True, default='', verbose_name='供应商报价备注')),
                ('cg_price', models.CharField(default='', max_length=30, verbose_name='采购成本')),
                ('cg_currency_icon', models.CharField(default='', max_length=10, verbose_name='采购成本币种符号')),
                ('supplier_code', models.CharField(default='', max_length=50, verbose_name='供应商代码')),
                ('level_text', models.CharField(default='', max_length=50, verbose_name='级别')),
                ('employees_text', models.CharField(default='', max_length=50, verbose_name='规模')),
                ('remark', models.TextField(blank=True, default='', verbose_name='供应商备注')),
                ('supplier_name', models.CharField(default='', max_length=255, verbose_name='供应商名称')),
                ('quotes', models.JSONField(blank=True, help_text='数组，元素格式：{currency, currency_icon, is_tax, tax_rate, step_prices: [{moq, price, price_with_tax}]}', null=True, verbose_name='报价数据')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_quotes', to='api_v1.lxlocalproduct', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': '供应商报价',
                'verbose_name_plural': '供应商报价列表',
                'db_table': 'lx_supplier_quote',
                'ordering': ['-id'],
            },
        ),
    ]
