# Generated by Django 5.1.2 on 2026-06-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0088_lxlocalproduct_lxproductcustomfield_lxproducttag_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LxSellers',
        ),
    ]
