# Generated by Django 5.1.2 on 2026-06-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0090_lxprofitreportmsku'),
    ]

    operations = [
        migrations.CreateModel(
            name='LxListingTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('global_tag_id', models.CharField(default='', max_length=50, verbose_name='标签 ID')),
                ('tag_name', models.CharField(default='', max_length=100, verbose_name='标签名称')),
                ('type', models.CharField(default='', max_length=50, verbose_name='标签类型')),
                ('color', models.CharField(default='', max_length=20, verbose_name='标签颜色')),
                ('create_by_name', models.CharField(default='', max_length=100, verbose_name='创建人名称')),
                ('modify_by_name', models.CharField(default='', max_length=100, verbose_name='最后编辑人名称')),
            ],
            options={
                'verbose_name': 'Listing 标签',
                'verbose_name_plural': 'Listing 标签列表',
                'db_table': 'lx_listing_tag',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='lxprofitreportmsku',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lxprofitreportmsku',
            name='query_type',
            field=models.IntegerField(choices=[(1, '按天'), (2, '按月')], default=1, help_text='1=按天，2=按月', verbose_name='查询类型'),
        ),
        migrations.AlterUniqueTogether(
            name='lxprofitreportmsku',
            unique_together={('query_type', 'report_date_month', 'posted_date_locale', 'sid', 'msku', 'asin', 'deferred_sub_status_code')},
        ),
    ]
