# Generated by Django 5.1.2 on 2026-06-16 04:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0091_lxlistingtag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lxlistingtag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lxlistingtag',
            name='status',
            field=models.CharField(choices=[('creating', '创建中'), ('normal', '正常'), ('modifying', '修改中'), ('deleted', '已删除')], default='creating', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='lxlistingtag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='lxlistingtag',
            name='global_tag_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='标签 ID'),
        ),
    ]
