# Generated by Django 5.1.2 on 2026-06-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0092_lxlistingtag_created_at_lxlistingtag_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lxlistingtag',
            name='status',
            field=models.CharField(choices=[('creating', '创建中'), ('normal', '正常'), ('modifying', '修改中'), ('deleting', '删除中')], default='creating', max_length=20, verbose_name='状态'),
        ),
        migrations.AddConstraint(
            model_name='lxlistingtag',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['creating', 'normal', 'modifying', 'deleting'])), fields=('tag_name',), name='uq_lx_listing_tag_name_active'),
        ),
    ]
