# Generated by Django 5.1.2 on 2026-07-02 01:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DifyApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='对外公开 ID')),
                ('code', models.CharField(help_text='英文 + 下划线小写代码，前端切换 chip 时携带此值，例：default / listing_image', max_length=40, unique=True, verbose_name='应用代码')),
                ('name', models.CharField(help_text='用户在 chip 上看到的中文名称，例："通用助手" / "Listing 图片生成"', max_length=80, verbose_name='应用名称')),
                ('description', models.TextField(blank=True, default='', help_text='下拉菜单中展示给用户的辅助说明文字', verbose_name='应用描述')),
                ('icon', models.CharField(default='💬', help_text='单个 emoji 字符，前端 chip 与列表头像渲染使用', max_length=10, verbose_name='应用图标')),
                ('mode', models.CharField(choices=[('chatflow', '聊天流'), ('agent', '智能体'), ('workflow', '工作流')], default='chatflow', max_length=20, verbose_name='应用类型')),
                ('api_base', models.CharField(blank=True, default='', help_text='留空时回退到 settings.DIFY_API_BASE', max_length=200, verbose_name='Dify Base URL')),
                ('api_key_encrypted', models.BinaryField(help_text='通过 cryptography.Fernet 加密的 sk-xxx 密钥，禁止在任何日志/响应中暴露', verbose_name='加密后的 API Key')),
                ('default_inputs', models.JSONField(blank=True, default=dict, help_text='调用 Dify 时合并到 inputs 的预置变量，例：{"thinking_mode": "off"}', verbose_name='默认 inputs 模板')),
                ('sort_order', models.IntegerField(db_index=True, default=0, help_text='前端下拉菜单按此值升序排列', verbose_name='展示顺序')),
                ('is_active', models.BooleanField(default=True, help_text='False 表示该应用不在前端切换器中展示', verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, help_text='前端首次打开时自动选中的应用；同一时刻应仅有一条为 True', verbose_name='是否为默认应用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': 'Dify 应用配置',
                'verbose_name_plural': 'Dify 应用配置',
                'db_table': 'dify_app',
                'ordering': ['sort_order', 'id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AiConversationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='对外公开 ID')),
                ('name', models.CharField(max_length=80, verbose_name='分组名称')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='展示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversation_groups', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': 'AI 对话分组',
                'verbose_name_plural': 'AI 对话分组',
                'db_table': 'ai_conversation_group',
                'ordering': ['order', 'created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AiConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='对外公开 ID')),
                ('pinned_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='置顶时间')),
                ('dify_conversation_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Dify 平台会话 ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='会话标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后活跃时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='ai.aiconversationgroup', verbose_name='所属分组')),
                ('dify_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='ai.difyapp', verbose_name='所属 Dify 应用')),
            ],
            options={
                'verbose_name': 'AI 对话会话',
                'verbose_name_plural': 'AI 对话会话',
                'db_table': 'ai_conversation',
                'ordering': ['-updated_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AiMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='对外公开 ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI 助手')], max_length=16, verbose_name='消息角色')),
                ('message_type', models.CharField(choices=[('text', '文本'), ('plan', '计划提案')], default='text', max_length=16, verbose_name='消息类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('streaming', '生成中'), ('done', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=16, verbose_name='生成状态')),
                ('content', models.TextField(blank=True, default='', verbose_name='消息正文')),
                ('raw_plan_json', models.JSONField(blank=True, null=True, verbose_name='Plan 原始 Schema')),
                ('dify_message_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Dify 平台消息 ID')),
                ('task_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Celery Task ID')),
                ('error_msg', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aiconversation', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': 'AI 对话消息',
                'verbose_name_plural': 'AI 对话消息',
                'db_table': 'ai_message',
                'ordering': ['conversation_id', 'created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AiPlanExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(db_index=True, max_length=64, verbose_name='Plan ID')),
                ('endpoint', models.CharField(max_length=200, verbose_name='调用端点')),
                ('payload', models.JSONField(verbose_name='请求载荷')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('success', '已执行'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=16, verbose_name='执行状态')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='执行结果')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_plan_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_execution', to='ai.aimessage', verbose_name='源消息')),
            ],
            options={
                'verbose_name': 'AI Plan 执行审计',
                'verbose_name_plural': 'AI Plan 执行审计',
                'db_table': 'ai_plan_execution',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='aiconversationgroup',
            index=models.Index(fields=['user', 'order'], name='ai_conversa_user_id_ebee50_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiconversationgroup',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_ai_group_user_name'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ai_message_convers_0cc073_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['user', '-updated_at'], name='ai_conversa_user_id_139fba_idx'),
        ),
    ]
